### DISCUSSION TITLE
Show off your config

### DISCUSSION THREAD

**Discussion by tfeldmann** [tfeldmann/organize#116] [General]
Since there isn't any tracking in organize I don't know what it is mostly used for. So it would be very interesting to see what you use this for and what can be optimized!
Got some clever rules? Show 'em!

**Comment by wintuxx** [comment]
```
all_folders: &all
   - '/media/usbhdd/Programme/'
   - '/media/usbhdd/Archive/'
   - '/media/usbhdd/ISOs/'

rules:

# verschiebe Dokumente nach Dokumentordner
   - folders:
      - /media/usbhdd/Downloads/
     filters:
          - extension:
             - pdf
             - doc
             - txt
     actions:
          - move: '/media/usbhdd/Dokumente/'
     subfolders: false

# verschiebe Videos in den Ordner Videos
   - folders:
          - /media/usbhdd/Downloads/
     filters:
          - extension:
                  - mp4
                  - avi
                  - mpeg
                  - mpg
     actions:
          - move: '/media/usbhdd/Videos/'
     subfolders: false

# verschiebe Dateien mit der Endung exe in den Ordner Programme
   - folders:
          - /media/usbhdd/Downloads/
     filters:
          - extension:
                  - exe
     actions:
          - move: '/media/usbhdd/Programme/'
     subfolders: false

# verschiebe rar in den Ordner Archive/rar
   - folders:
          - /media/usbhdd/Downloads/
     filters:
          - extension:
                  - rar
     actions:
          - move: '/media/usbhdd/Archive/rar/'
     subfolders: false

# verschiebe zip in den Ordner Archive/zip/
   - folders:
          - /media/usbhdd/Downloads/
     filters:
          - extension:
                  - zip
     actions:
          - move: '/media/usbhdd/Archive/zip/'
     subfolders: false
# verschiebe Bilder in den Ordner Bilder
   - folders:
          - /media/usbhdd/Downloads/
     filters:
          - extension:
                  - jpg
                  - jpeg
                  - png
                  - gif
                  - tif
                  - tiff
     actions:
          - move: '/media/usbhdd/Bilder/'
     subfolders: false

 # verschiebe tar in den Ordner Archive/tar
   - folders:
          - /media/usbhdd/Downloads/
     filters:
          - extension:
                  - tar
                  - .gz
     actions:
          - move: '/media/usbhdd/Archive/tar/'
     subfolders: false

# Lösche Dateien die älter sind als 1 Jahr
   - folders: *all

     filters:
          - lastmodified:
             years: 1
     actions:
          - delete
     subfolders: true

```

**Comment by wintuxx** [comment]
My new one:
```
all_folders: &all 
   - '/srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Programme/'
   - '/srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Archive/'
   - '/srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/ISOs/'
   - '! /srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Programme/**/*'

rules:

# Lösche Dateien die älter sind als 1 Jahr
   - folders: *all

     filters:
          - lastmodified:
                  years: 1
     actions:
          - delete
     subfolders: true

# verschiebe Dateien mit der Endung exe in den Ordner Programme
   - folders:
          - /srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Downloads/
     filters:
          - extension:
                  - exe
            case_sensitive: false
          - lastmodified:
                  hours: 4
     actions:
          - move: '/srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Programme/'
     subfolders: false

# verschiebe Dokumnete in den Ordner Dokumente
   - folders:
          - /srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Downloads/
     filters:
          - extension:
                  - txt
                  - doc
                  - pdf
                  - docx
            case_sensitive: false
          - lastmodified:
                  hours: 4
     actions:
          - move: '/srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Dokumente/{extension.upper}/'
     subfolders: false

# verschiebe Videos in den Ordner Videos
   - folders:
          - /srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Downloads/
     filters:
          - extension:
                  - mp4
                  - avi
                  - mpeg
                  - mpg
                  - mov
                  - mkv
                  - flv
                  - m4v
                  - 3gp
                  - wmv
            case_sensitive: false
          - lastmodified:
                  hours: 4
     actions:
          - move: '/srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Videos/'
     subfolders: false

# verschiebe Bilder in den Ordner Bilder
   - folders:
          - /srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Downloads/
     filters:
          - extension:
                  - jpg
                  - jpeg
                  - png
                  - gif
                  - tif
                  - tiff
                  - ico
                  - bmp
                  - svg
                  - psd
            case_sensitive: false
          - created
     actions:
          - move: '/srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Bilder/{extension.upper}/{created.year}/{created.month}/{created.day}/'
     subfolders: false

# verschiebe gepackte Dateien in den Ordner Archive
   - folders:
          - /srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Downloads/
     filters:
          - extension:
                  - rar
                  - zip
                  - 7z
                  - tar
                  - .gz
            case_sensitive: false
          - lastmodified:
                  hours: 4
     actions:
          - move: '/srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Archive/{extension.upper}/'
     subfolders: false

# verschiebe Musik in den Ordner Musik 
   - folders:
          - /srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Downloads/
     filters:
          - extension:
                  - mp3
                  - wav
                  - ogg
          - filename:
                  startswith:
                     - A
                     - a
            case_sensitive: false
     actions:
          - move: '/srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Musik/{extension.upper}/A/'
     subfolders: false

   - folders:
          - /srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Downloads/
     filters:
          - extension:
                  - mp3
                  - wav
                  - ogg
          - filename:
                  startswith:
                     - B
                     - b
            case_sensitive: false
     actions:
          - move: '/srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Musik/{extension.upper}/B/'
     subfolders: false

   - folders:
          - /srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Downloads/
     filters:
          - extension:
                  - mp3
                  - wav
                  - ogg
          - filename:
                  startswith:
                     - C
                     - c
            case_sensitive: false
     actions:
          - move: '/srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Musik/{extension.upper}/C/'
     subfolders: false

   - folders:
          - /srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Downloads/
     filters:
          - extension:
                  - mp3
                  - wav
                  - ogg
          - filename:
                  startswith:
                     - D
                     - d
            case_sensitive: false
     actions:
          - move: '/srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Musik/{extension.upper}/D/'
     subfolders: false

   - folders:
          - /srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Downloads/
     filters:
          - extension:
                  - mp3
                  - wav
                  - ogg
          - filename:
                  startswith:
                     - E
                     - e
            case_sensitive: false
     actions:
          - move: '/srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Musik/{extension.upper}/E/'
     subfolders: false

   - folders:
          - /srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Downloads/
     filters:
          - extension:
                  - mp3
                  - wav
                  - ogg
          - filename:
                  startswith:
                     - F
                     - f
            case_sensitive: false
     actions:
          - move: '/srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Musik/{extension.upper}/F/'
     subfolders: false

   - folders:
          - /srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Downloads/
     filters:
          - extension:
                  - mp3
                  - wav
                  - ogg
          - filename:
                  startswith:
                     - G
                     - g
            case_sensitive: false
     actions:
          - move: '/srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Musik/{extension.upper}/G/'
     subfolders: false

   - folders:
          - /srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Downloads/
     filters:
          - extension:
                  - mp3
                  - wav
                  - ogg
          - filename:
                  startswith:
                     - H
                     - h
            case_sensitive: false
     actions:
          - move: '/srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Musik/{extension.upper}/H/'
     subfolders: false

   - folders:
          - /srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Downloads/
     filters:
          - extension:
                  - mp3
                  - wav
                  - ogg
          - filename:
                  startswith:
                     - I
                     - i
            case_sensitive: false
     actions:
          - move: '/srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Musik/{extension.upper}/I/'
     subfolders: false

   - folders:
          - /srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Downloads/
     filters:
          - extension:
                  - mp3
                  - wav
                  - ogg
          - filename:
                  startswith:
                     - J
                     - j
            case_sensitive: false
     actions:
          - move: '/srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Musik/{extension.upper}/J/'
     subfolders: false

   - folders:
          - /srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Downloads/
     filters:
          - extension:
                  - mp3
                  - wav
                  - ogg
          - filename:
                  startswith:
                     - K
                     - k
            case_sensitive: false
     actions:
          - move: '/srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Musik/{extension.upper}/K/'
     subfolders: false

   - folders:
          - /srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Downloads/
     filters:
          - extension:
                  - mp3
                  - wav
                  - ogg
          - filename:
                  startswith:
                     - L
                     - l
            case_sensitive: false
     actions:
          - move: '/srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Musik/{extension.upper}/L/'
     subfolders: false

   - folders:
          - /srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Downloads/
     filters:
          - extension:
                  - mp3
                  - wav
                  - ogg
          - filename:
                  startswith:
                     - M
                     - m
            case_sensitive: false
     actions:
          - move: '/srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Musik/{extension.upper}/M/'
     subfolders: false


   - folders:
          - /srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Downloads/
     filters:
          - extension:
                  - mp3
                  - wav
                  - ogg
          - filename:
                  startswith:
                     - N
                     - n
            case_sensitive: false
     actions:
          - move: '/srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Musik/{extension.upper}/N/'
     subfolders: false

   - folders:
          - /srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Downloads/
     filters:
          - extension:
                  - mp3
                  - wav
                  - ogg
          - filename:
                  startswith:
                     - O
                     - o
            case_sensitive: false
     actions:
          - move: '/srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Musik/{extension.upper}/O/'
     subfolders: false

   - folders:
          - /srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Downloads/
     filters:
          - extension:
                  - mp3
                  - wav
                  - ogg
          - filename:
                  startswith:
                     - P
                     - p
            case_sensitive: false
     actions:
          - move: '/srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Musik/{extension.upper}/P/'
     subfolders: false

   - folders:
          - /srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Downloads/
     filters:
          - extension:
                  - mp3
                  - wav
                  - ogg
          - filename:
                  startswith:
                     - Q
                     - q
            case_sensitive: false
     actions:
          - move: '/srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Musik/{extension.upper}/Q/'
     subfolders: false

   - folders:
          - /srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Downloads/
     filters:
          - extension:
                  - mp3
                  - wav
                  - ogg
          - filename:
                  startswith:
                     - R
                     - r
            case_sensitive: false
     actions:
          - move: '/srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Musik/{extension.upper}/R/'
     subfolders: false

   - folders:
          - /srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Downloads/
     filters:
          - extension:
                  - mp3
                  - wav
                  - ogg
          - filename:
                  startswith:
                     - S
                     - s
            case_sensitive: false
     actions:
          - move: '/srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Musik/{extension.upper}/S/'
     subfolders: false

   - folders:
          - /srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Downloads/
     filters:
          - extension:
                  - mp3
                  - wav
                  - ogg
          - filename:
                  startswith:
                     - T
                     - t
            case_sensitive: false
     actions:
          - move: '/srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Musik/{extension.upper}/T/'
     subfolders: false

   - folders:
          - /srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Downloads/
     filters:
          - extension:
                  - mp3
                  - wav
                  - ogg
          - filename:
                  startswith:
                     - U
                     - u
            case_sensitive: false
     actions:
          - move: '/srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Musik/{extension.upper}/U/'
     subfolders: false

   - folders:
          - /srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Downloads/
     filters:
          - extension:
                  - mp3
                  - wav
                  - ogg
          - filename:
                  startswith:
                     - V
                     - v
            case_sensitive: false
     actions:
          - move: '/srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Musik/{extension.upper}/V/'
     subfolders: false

   - folders:
          - /srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Downloads/
     filters:
          - extension:
                  - mp3
                  - wav
                  - ogg
          - filename:
                  startswith:
                     - W
                     - w
            case_sensitive: false
     actions:
          - move: '/srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Musik/{extension.upper}/W/'
     subfolders: false

   - folders:
          - /srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Downloads/
     filters:
          - extension:
                  - mp3
                  - wav
                  - ogg
          - filename:
                  startswith:
                     - X
                     - x
            case_sensitive: false
     actions:
          - move: '/srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Musik/{extension.upper}/X/'
     subfolders: false

   - folders:
          - /srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Downloads/
     filters:
          - extension:
                  - mp3
                  - wav
                  - ogg
          - filename:
                  startswith:
                     - Y
                     - y
            case_sensitive: false
     actions:
          - move: '/srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Musik/{extension.upper}/Y/'
     subfolders: false

   - folders:
          - /srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Downloads/
     filters:
          - extension:
                  - mp3
                  - wav
                  - ogg
          - filename:
                  startswith:
                     - Z
                     - z
            case_sensitive: false
     actions:
          - move: '/srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Musik/{extension.upper}/Z/'
     subfolders: false

   - folders:
          - /srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Downloads/
     filters:
          - extension:
                  - mp3
                  - wav
                  - ogg
          - filename:
                  startswith:
                     - Ä
                     - ä
                     - Ö
                     - ö
                     - Ü
                     - ü
            case_sensitive: false
     actions:
          - move: '/srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff//Musik/{extension.upper}/AE_UE_OE/'
     subfolders: false

   - folders:
          - /srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Downloads/
     filters:
          - extension:
                  - mp3
                  - wav
                  - ogg
          - filename:
                  startswith:
                     - 0
                     - 1
                     - 2
                     - 3
                     - 4
                     - 5
                     - 6
                     - 7
                     - 8
                     - 9
            case_sensitive: false
     actions:
          - move: '/srv/7e1c6d9c-f592-47bb-8230-e6a8b75907ff/Musik/{extension.upper}/0_9/'
     subfolders: false
```

**Comment by dunxd** [comment]
Not very complex, but this is what I use to sync full resolution photos from my Android phone to my Mac via OneDrive.  OneDrive copies the pictures into the Camera Roll folder, and by moving them out of this I don't use space on OneDrive for long.

```yaml
# Organize rules for syncing photos and videos from phone via OneDrive
#
# This config is run using a Folder Action in Automator that watches the OneDrive 
# Camera Roll folder for new items.  They are then moved to My Photos/Year/Month 
# folder. 
#
# See Organize docs at https://github.com/tfeldmann/organize
rules:
  # Move photos into Year/Month folders in My Photos
  - folders: ~/OneDrive/Pictures/Camera Roll
    filters:
    - extension: jpg
    - created
    actions:
    - move: ~/Pictures/My Photos/{created.year}/{created.month:02}/
    
  # Move videos and animated GIFs into Year/Month folders in Movies
  - folders: ~/OneDrive/Pictures/Camera Roll
    filters:
    - extension:
      - mp4
      - gif
    - created
    actions:
    - move: ~/Movies/My Videos/{created.year}/{created.month:02}/
```

I then created a Folder Action in Automate that calls organize with this config when items are added to the Camera Roll folder
`/usr/local/bin/organize run --config-file=~/Organize/Sync\ From\ OneDrive.yaml`

**Comment by snuffop** [comment]
This below moves images to Daily directories based on the created date and time
```

 - folders: ~/Downloads
    filters:
      - extension:
        - png
        - jpg
        - jpeg
        - gif
        - tiff
        - eps
      - created:
          timezone: "EST5EDT"
    actions:
      - echo: "Found Image File"
      - move: '~/Nextcloud/Pictures/2020 - 2029/{created.year}/{created.month:02}/Daily/{created.day:02}/'

```

OUTPUT
Folder /home/ext/Downloads:
  File 2021-10-11-134522_608x1274_scrot.png:
    - [Echo] Found Image File
    - [Move] Move to "/home/marty/Nextcloud/Pictures/2020 - 2029/2021/10/Daily/11/2021-10-11-134522_608x1274_scrot.png"

**Comment by kisst** [comment]
````
  - name: Remove old partial downloads
    locations: ~/Downloads
    filters:
      - extension:
          - download
          - crdownload
          - part
      - lastmodified:
          days: 30
          mode: older
    actions:
      - trash
```

**Comment by kisst** [comment]
```
  - name: Appimages
    locations: ~/Downloads
    filters:
      - extension:
          - AppImage
    actions:
      - move: ~/bin/
      - shell: 'chmod +x "{path}"'
```

**Comment by kisst** [comment]
```
  - name: Archive old downloads
    locations: ~/Downloads
    filters:
      - lastmodified:
          days: 30
          mode: older
      - created
    actions:
      - move: "~/Downloads/archive/{created.year}/{created.month}/"
```

**Comment by kisst** [comment]
```
  - name: FreeNAS config backups
    locations: ~/Downloads
    filters:
      - regex: '^freenas-\d{14}\.db$'
    actions:
      - move: /mnt/backup/
```

**Comment by kisst** [comment]
```
  - name: Upload to paperless
    locations: ~/Downloads
    filter_mode: any
    filters:
      - regex: '^Payroll\ settlement.*\.pdf$'
      - regex: '^.*[mM]ynameregex\.(pdf|docx?)$'
      - regex: '^.*Other Important Doc Name Patterns.*\.pdf$'
    actions:
      - python: |
          import os, requests, dotenv
          dotenv.load_dotenv(os.path.expanduser('~/.config/paperless.env'))
          url = os.getenv('URL')
          token = os.getenv('TOKEN')
          headers = {'Authorization': f'Token {token}'}
          with open(path, 'rb') as file:
              response = requests.post(url, headers=headers, files={'document': file})
          print(response.content)
          if response.status_code == 200:
              os.remove(path)
   ````

**Reply by tfeldmann** [reply]
Cool idea!

**Comment by kisst** [comment]
```
  - name: "New images"
    subfolders: True
    locations:
      - "."
    filters:
      - extension:
        - jpg
        - png
        - gif
      - python: |
          import os
          import datetime
          from PIL import Image
          try:
              image = Image.open(path)
              exif_data = image.getexif()
              # See exif tags at https://exiv2.org/tags.html
              if 36867 in exif_data:
                  data_src = "Exif.Image.DateTimeOriginal"
                  taken_time = exif_data[36867]
                  year, month, day = taken_time.split()[0].split(":")
              elif 306 in exif_data:
                  data_src = "Exif.Image.DateTime"
                  taken_time = exif_data[306]
                  year, month, day = taken_time.split()[0].split(":")
              else:
                  data_src = "Filesystem ctime"
                  created_time = os.path.getctime(path)
                  created_time = datetime.datetime.fromtimestamp(created_time)
                  year, month, day = created_time.year, created_time.month, created_time.day
              return {"year": year, "month": month, "day": day, "data_src": data_src}
          except (AttributeError, KeyError, IndexError) as exc:
              print(exc)
              # Just return the current date
              now = datetime.datetime.now()
          return {"year": now.year, "month": now.month, "day": now.day, "data_src": "FailbackToday"}
      - exif
    actions:
      - echo: "Based on {python.data_src } {path} should go to {python.year}/{python.month}/{python.day}/"
      - move: 
          dest: "/mymountpoint/pictures/{python.year}/{python.month}/{python.day}/"
          on_conflict: skip
```

**Reply by AdelleBernal** [reply]
Great! If you want to destination to be in the same folder where you act the action, woudl this be ok? 

 - move: 
          dest: "./{python.year}/{python.month}/{python.day}/"
          on_conflict: skip

**Comment by marcelbrueckner** [comment]
Like @kisst I use organize together with Paperless-ngx. In my case, I run it to extract certain information from the file content and push it to Paperless-ngx via its REST API. Details [here](https://paperless.sh/post-consumption/content-matching/), config below.

```yaml
# organize configuration file
# https://organize.readthedocs.io

# YAML ANCHORS
# This filters the exact document that has been consumed
.locations: &current_document
  - path: "{env.DOCUMENT_ARCHIVE_DIR}"
    filter:
      # Needs to be replaced with e.g. `envsubst`
      # as organize doesn't replace environment placeholders in filter
      - "$DOCUMENT_ARCHIVE_FILENAME"

# RULES
rules:
  - name: "Nabu Casa invoice"
    locations: *current_document
    filters:
      - filecontent: "Nabu Casa"
      - filecontent: "(?P<title>Home Assistant Cloud)"
      - filecontent: 'Amount due.*(?P<amount>\d{2}\.\d{2})'
    actions:
      - echo: "Home Assistant hooray"
      - shell: "./pngx-update-document.py --url http://localhost:8000 --document-id {env.DOCUMENT_ID} --title '{filecontent.title}' --custom-field-id 1 --custom-field-value {filecontent.amount}"
      - echo: "{shell.output}"
```
