### DISCUSSION TITLE
variable Location using regex?

### DISCUSSION THREAD

**Discussion by rjCousineau** [tfeldmann/organize#223] [Q&A]
Hi, 
I'm looking to parse the filename using regex and move into custom dir according to filename.

Eg. 
  foo.pdf

Parse the name and move to folder ~/foo/

Is this possible?

```
# organize configuration file
# https://organize.readthedocs.io

rules:
  - locations:
      - ~/python/watch/
    filters:
      - regex: '^(?P<name>.*)\.(?P<extension>.*)$'
    actions:
      - python:
          code: |
            print('Name: %s' % regex["name"])
          run_in_simulation: yes
      - move: ~/regex["name"]/
```

simulation results
```
  FOO.pdf
    - (python) Running python script.
    - (python) Name: FOO
    - (python) Extension: pdf
    - (move) Move to ~/regex["name"]/FOO.pdf
```
