### DISCUSSION TITLE
"(move) ERROR! 'created' is undefined" when sorting photos

### DISCUSSION THREAD

**Discussion by tehabe** [tfeldmann/organize#249] [Q&A]
I'm trying to sort my photos and I was able to create this rule with the "documenation" but I'm getting the error message that "created" is not defined. How do I define it?

```
rules:
  - locations: "~/Pictures/PhotoFiles/"
    subfolders: true
    actions:
     - move:
        dest: "~/Pictures/Sortiert/{created.strftime('%Y-%m-%d')}/"
        on_conflict: skip
```

I actually want to have a folder structure like (year)/(month)/day/. But I'm currently just want to make it at least work.

**Comment by tfeldmann** [comment]
You have to add the `created` filter for the placeholder to work:

```yaml
rules:
  - locations: "~/Pictures/PhotoFiles/"
    subfolders: true
    filters:
     - created
    actions:
     - move:
        dest: "~/Pictures/Sortiert/{created.strftime('%Y-%m-%d')}/"
        on_conflict: skip
```

> I actually want to have a folder structure like (year)/(month)/day/. But I'm currently just want to make it at least work.

You can achieve this by formatting the date with slashes: `{created.strftime('%Y/%m/%d')}`

**Reply by tehabe** [reply]
Thank you, it works, I tried something like it but I must have made a mistake or something. Now I just have to figure out how to use the "correct" creation date from the EXIF metadata. Maybe the homebrew version of organize is missing something for that.

**Reply by tfeldmann** [reply]
You can use something like this:

```yaml
rules:
  - locations: ~/Pictures
    filters:
      - exif
    actions:
      - echo: "{exif}"
```

 To see which exif information is available in your pictures. The exif datetimes are currently not yet automatically converted to python `datetime`s, so formatting this might be a bit tricky, but can be done with string operations. Reply here if you need help with that 👍
