### DISCUSSION TITLE
Sorting in folders based on EXIF data

### DISCUSSION THREAD

**Discussion by telometto** [tfeldmann/organize#265] [Q&A]
Does anyone know if it is possible to create folders based on EXIF data? I'd like to sort them in the following order: year > month > day.
```yml
# organize configuration file
# https://organize.readthedocs.io
aud_ext: &aud
  - bmp
  - cr2
  - gif
  - heic
  - jpeg
  - jpg
  - mrk
  - njb
  - png
  - webp

rules:
  - name: "Organize pictures by EXIF"
    locations:
      - path: "/mnt/pictures/"
    subfolders: true
    filters:
      - exif
      - name
      - extension: *aud
    actions:
      - echo: "{path}"
      - move: "/mnt/pictures/{exif.strftime('%Y')}/{exif.strftime('%m')}/{exif.strftime('%d')}/{extension.lower()}/{name | replace(' ', '_') | lower()}.{extension.lower()}"
```
