### DISCUSSION TITLE
Setting a destination directory on a samba file server

### DISCUSSION THREAD

**Discussion by ashaikh** [tfeldmann/organize#276] [Q&A]
How would you set the destination directory to a samba folder share, I can't find it in the docs and I was not able to make this work.
I tried:
1)          dest: 'smb://Tower.local/docs/incoming/'
2)          dest: '//Tower.local/docs/incoming/'

Thank you

```
rules:
  - name: "pdf"
    locations: /home/T/pdownload/
    subfolders: true
    filters:
      - extension: 
        - .pdf
    actions:
      - echo: "Found pdf!"
      - move: 
          dest: 'smb://Tower.local/docs/incoming/'
          on_conflict: "overwrite"
```
