### DISCUSSION TITLE
Specify date range with two created filters. What is the best method?

### DISCUSSION THREAD

**Discussion by 89sundown** [tfeldmann/organize#431] [Q&A]
I'm a bit confused on how to create a date range with the [created filter](https://organize.readthedocs.io/en/latest/filters/#created). Is this possible with the below? 

I'm doing this in windows.

```
  - name: Move dirs from Downloads that are between 3 and 4 years old 2021 2022
    enabled: True
    targets: files
    locations:
      - path: C:\Users\user1\Downloads
        max_depth: 1
    filter_mode: "all"  # Both filters must match
    filters:
      - created:                    # 01/01/2022
          years: 3
          months: 1
          days: 13
          mode: older
      - created:                    # 01/01/2021
          years: 4
          months: 1
          days: 13
          mode: newer
    actions:
      - move: C:\Users\user1\Downloads\2021-2022
```
