### DISCUSSION TITLE
".partial" for files still transferring

### DISCUSSION THREAD

**Discussion by nothing2obvi** [tfeldmann/organize#441] [Q&A]
Hello!

Firstly, organize is terrific. I'm just wondering if there's a way to make files that are still being moved/copied/etc. to have something like ".partial" at the end of the file name until the file transfers are fully completed. Thanks!

**Comment by tfeldmann** [comment]
Thanks! What do you need this for? You could do it like this (untested):

```yaml
actions:
   - copy: "target.ext.partial"
   - rename: "target.ext"
```
