### DISCUSSION TITLE
Renaming PDF based on specific date found

### DISCUSSION THREAD

**Discussion by MyVizDrake** [tfeldmann/organize#449] [Q&A]
Hi everyone! 

Organize and regex noob here ...

Trying to find a replacement for the MacOS app Hazel and one of the really cool features is to specify in the content match which date to capture as a variable in order to do date-math. Best example is a Credit Card billing statement which has things like ...

Billing Period: 03/12/24-04/09/24

In the above case I would tell Hazel to match the 2nd date (04/09/24) and then rename the file to 'some_credit_card_202404.pdf' and move it somewhere.  Manipulating the detected 2nd date from MM/DD/YY to be YYYYMM.

I think it can kind of be done with ```- filecontent: '^Billing Period: \d{2}\/\d{2}\/\d{2}-(?P<statement_date>.*)'``` to capture 04/09/24 as statement_date but when I run ```organize sim``` on the PDF in question it reports "Nothing to do"

It's possible my action is messed up and it can't figure out what to do. I was simply trying to find the file(s) first and then simply show I captured the variable.

I am running organize via a scoop.sh installation of Python (3.13) and have poppler installed via scoop.sh as well.  I can confirm that I can run pdf2totext on the PDF in question from a shell and I get a txt version of the PDF in question.

The config
```rules:
  - name: "Test Rule"
    locations: "D:\\Folder 1\\Folder 2\\Folder 3\\Files"
    subfolders: true
    filters:
      - extension: pdf
      - filecontent: '^Billing Period: \d{2}\/\d{2}\/\d{2}-(?P<statement_date>.*)'
    actions: 
      - echo: 'Found a {extension.upper()} with a credit card statement date of "{statement_date}": "{name}"'
```  
I also did a basic check of the regex on the string in question (regex101.com) and it behaved as-expected.

What have I done wrong?

Thanks in advance!

Scott

Bonus points if you can give me a hint as to how to how to manipulate the statement date from MM/DD/YY to YYYYMM but I suspect I'll need to use the python action to handle that part.  Baby steps 1st. :-)

**Comment by rkuzner** [comment]
Hi @MyVizDrake!

I Had a similar problem trying to match credit card statements with start and end dates for billing periods.
The rule I got finally working goes like this (many filecontent conditions removed & without PII):

```
  - name: "Card Statemenst: Bank XYZ"
    enabled: true
    tags:
      - pdf_rename
    locations: *bank_folders
    targets: files
    filters:
      - name
      - extension:
        - pdf
    #  - filecontent
      - filecontent: 'Period[ ]+(?P<period_start_day>\d{2}\/\d{2}\/\d{2,4})[ ]+to[ ]+(?P<statement_day>\d{2})\/(?P<statement_month>\d{2})\/(?P<statement_year>\d{2,4})'
    actions:
      - python:
          run_in_simulation: yes
          code: |
            statement_full_year = filecontent["statement_year"]
            if len(statement_full_year) <= 2:
              statement_full_year = "20" + statement_full_year

            target_filename_date = statement_full_year+"-"+filecontent["statement_month"]+"-"+filecontent["statement_day"]+" "
            target_filename_desc = " Account-"+name[-4:]

            return {
              "target_folder": "Banks/XYZ/"+statement_full_year,
              "target_filename": target_filename_date+"-"+target_filename_desc+".pdf",
            }
    #  - echo: "Contents : {filecontent}"
    #  - echo: "Target Folder   : {python.target_folder}"
    #  - echo: "Target Filename : {python.target_filename}"
      - move:
          dest: "~/OneDrive/Documents/Statements/{python.target_folder}/{python.target_filename}"
          on_conflict: "skip"
 
```

as per debbugging the rule, I start with a broad filter & gradually uncommenting fine grainded filter conditions
```
      - filecontent
    #  - filecontent: 'Bank XYZ'
    #  - filecontent: 'Monthly Statement'
    ```

and uncommented actions
``` 
      - echo: "Contents : {filecontent}"
```


Some other things to note:
- I use regex101 for testing & refining regex expressions (always with output from the "echo contents")
- Some Banks have their PDF statements encrypted, sometimes with password and sometimes without password (blank password), in either case I use QPDF to detect & remove encryption. Some PDF previewers try the empty password and if it works show the PDF without any hint that it was encrypted, thus organize might not be able to read its contents.

I hope this helps!
