### ISSUE TITLE
Created filter

### ISSUE THREAD

**Issue by AT181903** [tfeldmann/organize#101]
There is a problem with 1 number months. For example January is returned as 1 instead of 01. Please correct this.

**Comment by tfeldmann** [comment]
Hi, yes I agree this is something you can stumble over. For the moment you can use the return value like this `{created.month:02}/`. For example:

```yaml
rules:
  - folders: ~/Documents/**/*
    filters:
      - extension:
          - pdf
          - docx
      - created
    actions:
      - move: '~/Documents/{extension.upper}/{created.year}{created.month:02}/'
      - shell: 'open "{path}"'
```
