### ISSUE TITLE
rename based on output of shell

### ISSUE THREAD

**Issue by quintrino** [tfeldmann/organize#107]
I have a number of files like
`this is a file.md`
I'd like to be able to rename them by replacing the spaces with _
to 
`this_is_a_file.md`

I can see the rename action allows for using variables like name/type/date/etc, but I can't see if there's a way to rename using substitution. Is this feature currently supported?

**Comment by tfeldmann** [comment]
No, thats currently not included. But you can easily create it yourself with whatever logic you need:

```yaml
- folders:
    - "~/Desktop/test"
  filters:
    - python: |
        if " " not in path.stem:
          return False
        clean_name = path.stem.replace(" ", "_") + path.suffix
        return {
          "clean_name": clean_name
        }
  actions:
    - rename: "{python.clean_name}"
```
