### ISSUE TITLE
Formatting date/time values

### ISSUE THREAD

**Issue by lensaffair** [tfeldmann/organize#108]
I use ```organize``` to, well, organize my invoices. Since most invoices don't have a sortable date in their filenames, I'd like to rename those files.

For example:
```~/Downloads/organize/someInvoiceFromApril.pdf```
should be moved/renamed to
```~/Documents/Invoices/04_someInvoiceFromApril.pdf```

With the following config, it works almost fine:
```
  rules:
    - folders:
        - ~/Downloads/organize
      filters:
        - created
        - filename:
            contains: someInvoice
      actions:
        - copy: '~/Documents/Invoices/{created.month}_{path.name}'
```

The thing is: the rename operation leads to ```4_someInvoiceFromApril``` and not to  ```04_someInvoiceFromApril```. Is there a way to format ```{created.month}``` to display that leading zero for one-digit-months?

PS: I really love your work here! On Windows I used DropIt, but since I switched to Linux, I've been looking for an alternative. Thanks for providing this nice and clean solution!

**Comment by lensaffair** [comment]
Oops, just found my answer.
```
  rules:
    - folders:
        - ~/Downloads/organize
      filters:
        - created
        - filename:
            contains: someInvoice
      actions:
        - copy: '~/Documents/Invoices/{created.month:02}_{path.name}'
```

:)
