### ISSUE TITLE
Slicing/substring of {path}-Strings

### ISSUE THREAD

**Issue by lensaffair** [tfeldmann/organize#110]
I throw all invoices from a specific vendor in my `organize`-folder. I'd like to organize these invoices based on a `{year}/{month}` folder structure. Those `{year}/{month}`-values can be derived from the filename (NOT from the file's creation date!). An example file might look like this:
`Invoice_46231578651_2021_04_14.pdf`

Let's just focus on the `{year}` now. So far, I have setup this rule:
```
  - folders:
      - ~/Downloads/organize
    filters:
      - extension: pdf
      - filename:
          contains: Invoice_
    actions:
      - echo: "{path.name[20:23]}"
```
Unfortunately, all I get upon execution is an error:
`[Echo] ERROR! string indices must be integers`

If I only pass one integer value, it works fine. `echo: "{path.name[20]}"` gives me the desired output `2`. 
Now, I _could_ concatenate a whole lot of these one-letter-substrings, but I wonder: why doesn't [slicing](https://stackoverflow.com/questions/509211/understanding-slice-notation) work here? Or does it, and I need to address the slice differently?

**Comment by tfeldmann** [comment]
That's because organize uses the standard python string formatting, so your action behaves like this (which is not valid python unfortunately).

```python
"{path.name[20:23]}".format(path=path)
```

I have a similar rule for my invoices and I found the regex filter much easier to use and more robust. For example:

```yaml
- folders: '~/Desktop/Test'
  filters:
    # 
    - regex: Invoice_\d+_(?P<year>\d+)_(?P<month>\d+)_(?P<day>\d+)\.pdf
  actions:
    - move: '~/Documents/Invoices/{regex.year}/{regex.month}/'
```

Hope this helps!
