### ISSUE TITLE
macOS tags

### ISSUE THREAD

**Issue by Marty56** [tfeldmann/organize#112]
I love this project and use it quite a lot.

I would be great if organize could also support tagging under MacOS.
Library for setting tags seems to be available 
https://pypi.org/project/macos-tags/

**Comment by tfeldmann** [comment]
Good idea! Do you want to set tags with organize or filter by tags?

**Comment by Marty56** [comment]
First priority to set tags but filter would also be nice.

**Comment by Marty56** [comment]
I am trying a workaround not be using the shell command in the yaml file

**Comment by tfeldmann** [comment]
Fastest solution would be to install the library with `pip3 install macos-tags` and then creating a custom python action like this:

```yaml
rules:
  - folders: ~/Desktop/test
    actions:
      - python: |
          import macos_tags
          macos_tags.add("Rot", file=path)
```

I have the `"Rot"` tag on my (German) system and this seems to work fine.

To see available tags, run:
```
python3 -c "import macos_tags as m;print(m.tags())"
```


But I'll look into creating a action for this!

**Comment by Marty56** [comment]
This is a great solution!
I am pretty clueless about python. I am already using it in trial error approach e.g. 

    filters:
      - extension: pdf
      - python: |
          return {"year": path.stem[0:4]}

I am using then {python.year} to create a folder and other things. So since there is only one - python statement in your rule syntax I would have to combine your approach above.

    filters:
      - extension: pdf
      - python: |
          import macos_tags
          macos_tags.add("Rot", file=path)
          return {"year": path.stem[0:4]}

I would try accordingly. And I am also not sure whether file=path needs to be customized.

**Comment by tfeldmann** [comment]
You nearly got it, but it should be a python action.
Your rule may look like this:

```yaml
filters:
  - extension: pdf
  - python: |
      return {"year": path.stem[0:4]}
actions:
  - python: |
      import macos_tags
      macos_tags.add("Rot", file=path)
```

`file=path` is correct and does not need to be modified. `path` is what comes out of the given filters.
