### ISSUE TITLE
file_ext, doesnotcontain

### ISSUE THREAD

**Issue by themacmarketer** [tfeldmann/organize#12]
Hi @tfeldmann,

Many thanks again for this fantastic utility.

Might there be a file_ext feature (similar to img_ext), that allow the matching of multiple file names?
e.g. I'd like the "Filename" rule below to match the filenames "love" or "patience".

Secondly is there any way to create a doesnotcontain match on the filename?

Thank you!

Ivan

@themacmarketer

```
rules:

  - folders: '~/Downloads'
    filters:
      - Filename:          
          contains: love          
          case_sensitive: false
      - LastModified          
    actions:
      - Move: '~/Downloads/FAITH/'
```

**Comment by tfeldmann** [comment]
Hi Ivan,
the upcoming release of organize includes a syntax to exclude files and folders. I'll let you know as soon as it is released 👍

**Comment by tfeldmann** [comment]
Version 1.4 now has support to exclude / include files via glob syntax.
https://organize.readthedocs.io/en/latest/page/config.html#excluding-files-and-folders

First make sure to update to the latest version:
```
pip install -U organize-tool
```

Now you can express your rule like this:
```yaml
rules:
  - folders:
      - '~/Downloads/*love*'
      - '~/Downloads/*patience*'
      - '! ~/Downloads/*exclude_this*'
    filters:
      - LastModified          
    actions:
      - Move: '~/Downloads/FAITH/'
```

So this is a workaround, I guess an option to match multiple names in `Filename` would be nicer. I added it to the todo list.

Greetings,
Thomas
