### ISSUE TITLE
Feature Request support of python functions

### ISSUE THREAD

**Issue by Marty56** [tfeldmann/organize#127]
I am storing my invoices with the following convention
YYYY-MM-DD_name of the invoice.

To process the date I have written the following  python filter that

```
      - python: |
          import textract
          import datetime

       #check valid date string beginning of filename
          date_string = path.stem[0:10]
          format = "%Y-%m-%d"
          result=True
          try:
            datetime.datetime.strptime(date_string, format)
          except ValueError:
            print("This is the incorrect date string format. It should be YYYY-MM-DD")
            result=False

       #calculate billing periode. New period is starting at April
          startofperiode = 4
          if (result):
            if ( int(path.stem[5:7]) >= startofperiode):
              period = (path.stem[0:4] + '-' + str(int(path.stem[0:4]) + 1))  
            else:
              period = ( str(int(path.stem[0:4]) - 1) + '-' + path.stem[0:4] )
       
       #remove blanks
            content = str(textract.process(str(path), errors="ignore")).replace(" ","" )

       #put further search logic here and calculate result
           if (........  );
              result = {"filter": filter,
                            "year":path.stem[0:4],
                            "period":period,
           else:
               result = False

          return result
```
This results into a pretty 'lengthy' python script that needs to be repeated for each rule.
It would be great if such scripts could be defined as functions that can be called in the python filter.

**Comment by tfeldmann** [comment]
You can already do this:

```yaml
my_python_script: &script |
  print("Hello World!")
  print(path)

rules:
  - folders:
      - ~/Desktop/
    actions:
      - python: *script

  - folders:
      - ~/Documents/
    actions:
      - python: *script
```
