### ISSUE TITLE
Random character is being added the path in my config 

### ISSUE THREAD

**Issue by joeySeal** [tfeldmann/organize#146]
Im running 1.10.1 and in my config I have a rule to move to `/home/joey/Downloads/veryfi_triage` but if I run `organize sim` it shows the path as `/home/joey/Downloads/veryfi_triage 2`. If I run `organize run` as expected it will create the path with the trailing 2

```
~ cat .config/organize/config.yaml                                                                   
rules:
# email amazon invoice
    - folders: ~/Downloads
      subfolders: false
      filters:
          - extension: pdf
          - filename:
                startswith:
                    - 'Amazon.com - Order'
                case_sensitive: true

      actions:
          - move: /home/joey/Downloads/veryfi_triage
          - Shell: 'killall organize'
~  organize sim                                                                                        ✔ 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ SIMULATION ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Folder /home/joey/Downloads:
  File Amazon.com - Order 112-4490967-8707404.pdf:
    - [Move] Move to "/home/joey/Downloads/veryfi_triage 2"
    - [Shell] $ killall organize
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ SIMULATION ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~  organize config --debug                                                                             ✔ 
/home/joey/.config/organize/config.yaml
Your configuration as seen by the parser:
'rules':
- 'actions':
  - 'move': '/home/joey/Downloads/veryfi_triage'
  - 'Shell': 'killall organize'
  'filters':
  - 'extension': 'pdf'
  - 'filename':
      'case_sensitive': !!bool 'true'
      'startswith':
      - 'Amazon.com - Order'
  'folders': '~/Downloads'
  'subfolders': !!bool 'false'

Config file syntax seems fine!
No config problems found.
```
