### ISSUE TITLE
On Monterey, getting "[Errno 1] Operation not permitted"

### ISSUE THREAD

**Issue by andyylin** [tfeldmann/organize#152]
My config file tries to move files from iCloud to Google Drive, but after upgrading to Monterey I'm getting a "ERROR! [Errno 1] Operation not permitted: ..." error. 

Is this some sort of security related setting that I need to change?

**Comment by tfeldmann** [comment]
Can you post your config?

**Comment by tfeldmann** [comment]
Please try again with the newly released v2.0.0.

**Comment by andyylin** [comment]
Sorry, I missed your request to see my config. Organize is still not working with Google Drive.

Here is my config file after migrating to v2 (slightly modified for privacy):
```
rules:
    # move screenshots into year/month/day folders
    - locations:
        - /Users/x/Pictures/InstantShot
      filters:
        - extension:
            - jpg
        - created
      actions:
        - move: "/Volumes/Google Drive/My Drive/_x/x/x/x (x)/{created.strftime('%Y')}/{created.strftime('%m')}/{created.strftime('%d')}/"
```

Still not working
