### ISSUE TITLE
'charmap' codec can't decode

### ISSUE THREAD

**Issue by Cinux90** [tfeldmann/organize#154]
Hi All,

while starting to use organize I will setup my rules before execute it on productive files.
Therefore I started to set up a easy config file:
```yml
rules:
  - folders: ~/tmp_doc-test
    subfolders: false
    filters:
      - extension: pdf 
      - filecontent: "Entgeltbescheinigung"
    actions:
      - echo: "Found PDF!"
      - copy: "~/tmp_doc-test/sortiert/Lohnzettel/"

```

And execute it as usual:

```bash
organize run
```

For some files i face Following issues:

```text
  File BWG.pdf:
    - (FileContent) ERROR! 'charmap' codec can't decode byte 0x9d in position 9796: character maps to <undefined>
```

I tried to resolve this issue but i have no Idea about the reason.
First of all I was thinking that's because the files charset is of type binary:
```bash
file -i BWG.pdf
BWG.pdf: application/pdf; charset=binary
```
But I have also other PDF files with charset `binary`

So I'm completely out of ideas.
Someone of you has any idea?
