### ISSUE TITLE
Excluding files/folders

### ISSUE THREAD

**Issue by simonsan** [tfeldmann/organize#157]
I want to exclude files from being handled through `organize` given on a special term in the filename, in my case it's `dnm_` (do not move).

How would I achieve this? 

I tried 

```yaml
do_not_move: &do_not_move
  - "! **/dnm_*"
```

but it seems, that it can't be a wildcard folder and needs to be a subfolder of something I already used.

This also not seems to work:

```yaml
filters:
  - filename:
      startswith: "! dnm_*"
```

Is there a way to exclude files and folders based on a naming scheme?

**Comment by simonsan** [comment]
It seems like using it in a reference as a glob for all folders is not supported or something, it seems to work if you use it for each folder like that

```yaml
desktop_folder: &desktop
  - "~/Desktop/"
  - "C:/Users/Public/Desktop"
  - "! ~/Desktop/dnm_*"
```

Which is a bit more maintenance effort though. Maybe it could be nice to add an `exclude` to filters to define that in a rule?

So we could use:

```yaml
filters:
  exclude:
    - filename:
        startswith: "dnm_*"
```

Which is then not based on the files/folders definition but just iterates through the list of all files/folders in that rule?

**Comment by tfeldmann** [comment]
I just released v2 where you can do:

In the [folder definition](https://organize.readthedocs.io/en/latest/locations/#location-options):

```yaml
rules:
  - locations:
      - path: "~/Desktop"
        exclude_dirs:
          - "dnm_*"
```

In the filters:

```yaml
filters:
  - not name:
      startswith: "dnm_*"
```
