### ISSUE TITLE
What happened to the `system_files` option?

### ISSUE THREAD

**Issue by andreoliwa** [tfeldmann/organize#166]
Hey, thanks for the new version!

What happened to the `system_files` option?

- I [searched the whole repo](https://github.com/tfeldmann/organize/search?q=system_files), and there are only 2 references:
  - [Some commented out tests](https://github.com/tfeldmann/organize/blob/45ee3b559026d4277a8fc3782eec58c23e514dd4/tests/core/test_config.py#L115)
  - [An old commit that points to files that don't exist anymore on the default branch](https://github.com/tfeldmann/organize/commit/116ef50e47b1563ac6d54e4422172b5377a8cd9e)
- [It is not mentioned in the upgrade docs as a removed feature](https://tfeldmann.github.io/organize/updating-from-v1/)

This is the error I'm getting:

```
❯ organize sim
organize 2.0.3
Config: "/Users/aa/Library/Application Support/organize/config.yaml"
Error: Invalid config file!
'organize rule configuration' Key 'rules' error:
Wrong key 'system_files' in {'locations': '~/Documents/', 'subfolders': True, 'system_files': True, 'filters': [{'name': {'startswith': '.DS_Store'}}], 'actions': ['trash']}```
```

My config:

```yaml
rules:
  - locations: ~/Documents/
    subfolders: true
    system_files: true
    filters:
      - name:
          startswith: .DS_Store
    actions:
      - trash
```

**Comment by tfeldmann** [comment]
Totally forgot documenting this one!
The option moved into the locations.
You overwrite the default system exclude files with an empty list.

```yaml
rules:
  - locations:
      - path: ~/Desktop/
        system_exclude_files: []
    subfolders: true
    filters:
      - name: .DS_Store
    actions:
      - trash
```

While testing your config I found a small bug, so please update to v2.0.4 first.
