### ISSUE TITLE
When on the same hard drive, the `move` action seems to be actually copying the file instead of renaming it to the new directory

### ISSUE THREAD

**Issue by andreoliwa** [tfeldmann/organize#168]
I'm trying the new version 2.0.3.

This is part of my config:

```
mobile_upload_folders: &mobile_upload
  - ~/OneDrive/Pictures/Camera Roll/
  - ~/OneDrive/Pictures/Download/

rules:
  - locations:
      - *mobile_upload
    subfolders: true
    filters:
      - name:
          startswith:
            - Screenshot_
            - Temp_File_For_Share
          case_sensitive: false
      - lastmodified:
          years: 1
          mode: newer
    actions:
      - rename: "~/OneDrive/New_Screenshots/{lastmodified.strftime('%Y/%m')}/"
```

I noticed that .MP4 files were taking too long to be moved.
I assume that, in version 1.x, these files were being renamed to the new directory.

Now they seem to be actually copied and created in the new location, even if it's on the same hard drive.
I also noticed that the creation date and modification date of the files is the current time, and not the original file time.

I tried using the `rename` action, but I get this error message:

> (rename) ERROR! The new name cannot contain slashes. To move files or folders use `move`.
