### ISSUE TITLE
Wrong key 'exclude_dirs'

### ISSUE THREAD

**Issue by soehlert** [tfeldmann/organize#169]
I'm not sure if this is a bug or merely a documentation issue.

```
$ organize check
Checking: /Users/soehlert/Library/Application Support/organize/config.yaml
...
snip
....
Wrong key 'exclude_dirs' in {'locations': ['~/Downloads'], 'exclude_dirs': ['! ~/Downloads/test'], 'subfolders':
False, 'filters': [{'created': {'days': 30, 'mode': 'older'}}], 'actions': ['trash']}

$ cat "/Users/soehlert/Library/Application Support/organize/config.yaml"
rules:
  # Old files
  - locations:
      - '~/Downloads'
    exclude_dirs:
      - '! ~/Downloads/test'
    subfolders: false
    filters:
      - created:
          days: 30
          mode: older
    actions:
      - trash
  
$ organize --version
organize, version 2.0.3
```
This errors out (I can share more of the output too if it's helpful)

```
$ cat "/Users/soehlert/Library/Application Support/organize/config.yaml"
rules:
  # Old files
  - locations:
      - '~/Downloads'
      - '! ~/Downloads/test'
    subfolders: false
    filters:
      - created:
          days: 30
          mode: older
    actions:
      - trash

$ organize check
Checking: /Users/soehlert/Library/Application Support/organize/config.yaml
Config is valid.

```

This config works, but according to the [migration guide](https://organize.readthedocs.io/en/latest/updating-from-v1/), this syntax is not valid anymore.
```
REMOVED: The exclamation mark exclude syntax (! ~/Desktop/exclude). See [Location options](https://organize.readthedocs.io/en/latest/locations/#location-options).
```

**Comment by tfeldmann** [comment]
Yes in that case the documentation is not as clear as it should be. Try something like this:

```yaml
rules:
  # Old files
  - locations:
      - path: '~/Downloads'
        exclude_dirs:
          - "test"
    subfolders: false
    filters:
      - created:
          days: 30
          mode: older
    actions:
      - trash
```

Note that if you disable the subfolders you don't need to exclude the `test` dir because it is never visited.
