### ISSUE TITLE
Monterey, Organize v2: Google Drive gives [Errno 1] Operation not permitted

### ISSUE THREAD

**Issue by andyylin** [tfeldmann/organize#170]
Sorry, I missed your request to see my config. Organize is still not working with Google Drive.

Here is my config file after migrating to v2 (slightly modified for privacy):
```
rules:
    # move screenshots into year/month/day folders
    - locations:
        - /Users/x/Pictures/InstantShot
      filters:
        - extension:
            - jpg
        - created
      actions:
        - move: "/Volumes/Google Drive/My Drive/_x/x/x/x (x)/{created.strftime('%Y')}/{created.strftime('%m')}/{created.strftime('%d')}/"
```

Simulation is successful, but upon running I get errors like:

```
 - (move) ERROR! unable to create /Volumes/Google Drive/My Drive/_x/x/x/x (x)/2022/01/18 ([Errno 1] Operation 
not permitted: '/Volumes/Google Drive/My Drive/_x/x/x/x (x)/2022/01/18')

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│                                                                                                  │
│ /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/organize/cli.py:86 │
│ in run_local                                                                                     │
│                                                                                                  │
│    83 │   │   config_dir, config_name = split(config_path)                                       │
│    84 │   │   config = open_fs(config_dir).readtext(config_name)                                 │
│    85 │   │   os.chdir(working_dir)                                                              │
│ ❱  86 │   │   core.run(rules=config, simulate=simulate)                                          │
│    87 │   except NeedsMigrationError as e:                                                       │
│    88 │   │   console.error(e, title="Config needs migration")                                   │
│    89 │   │   console.warn(                                                                      │
│ /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/organize/core.py:3 │
│ 09 in run                                                                                        │
│                                                                                                  │
│   306 │   console.summary(count)                                                                 │
│   307 │                                                                                          │
│   308 │   if count["fail"]:                                                                      │
│ ❱ 309 │   │   raise RuntimeWarning("Some actions failed.")                                       │
│   310                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeWarning: Some actions failed.

```

_Originally posted by @andyylin in https://github.com/tfeldmann/organize/issues/152#issuecomment-1032382637_

**Comment by iburunat** [comment]
I'm having an identical error when performing sim (success) and run (error) for the following rule:

```yaml
  - name: "DOWNLOADS {files} {moves image types into IMAGE}"
    locations: ~/Downloads
    enabled: true
    filters:
      - extension:
        - jpg
        - jpeg
        - png
        - jpeg
        - tiff
    actions:
      - move:
          dest: "/Downloads/IMAGE/"
          on_conflict: rename_new
          rename_template: "{name}_{counter}{extension}"
```

error:


```
success 5 / fail 1

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│                                                                                                  │
│ /Users/user/opt/anaconda3/lib/python3.7/site-packages/organize/cli.py:88 in run_local            │
│                                                                                                  │
│    85 │   │   config_dir, config_name = split(config_path)                                       │
│    86 │   │   config = open_fs(config_dir).readtext(config_name)                                 │
│    87 │   │   os.chdir(working_dir)                                                              │
│ ❱  88 │   │   core.run(rules=config, simulate=simulate)                                          │
│    89 │   except NeedsMigrationError as e:                                                       │
│    90 │   │   console.error(e, title="Config needs migration")                                   │
│    91 │   │   console.warn(                                                                      │
│ /Users/user/opt/anaconda3/lib/python3.7/site-packages/organize/core.py:329 in run                │
│                                                                                                  │
│   326 │   console.summary(count)                                                                 │
│   327 │                                                                                          │
│   328 │   if count["fail"]:                                                                      │
│ ❱ 329 │   │   raise RuntimeWarning("Some actions failed.")                                       │
│   330                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeWarning: Some actions failed.
```

**Comment by tfeldmann** [comment]
Google Drive seems to change the file and folder permissions - I guess that might be the problem. I guess it should work when you set the correct permissions - but be careful to not expose your files to the open web ([article](https://bolesblogs.com/2013/01/23/a-warning-about-google-drive-local-file-permissions-and-web-publishing/))

**Comment by iburunat** [comment]
Thanks, in my case it's not to do with Google Drive, as it just pertains the /Downloads folder in a MacOS system. It never spit this error in earlier versions. Unfortunately, I can't tell in which version started to give error.

**Comment by tfeldmann** [comment]
When I ran my first rule on the Downloads folder the system asked me whether I'd like to give access.
Maybe you have to add organize to "Full disk access" in the privacy settings?

**Comment by iburunat** [comment]
I didn't get asked. I have added `Full Disk Access` and `Files and Folders` permissions to `organize`. Additionally, I've  `chmod -R 777 Downloads`, but keeps getting the same error...

**Comment by iburunat** [comment]
Interestingly, I have identical rules like e.g.,

```yaml
  - name: "DOWNLOADS {files} {moves audio types into AUDIO}"
    locations: ~/Downloads
    enabled: true
    filters:
      - extension:
        - ogg
        - mp3
        - aiff
        - wav
        - aac
        - flac
        - 3gp
        - opus
        - wma
    actions:
      - move:
          dest: "~/Downloads/AUDIO/"
          on_conflict: rename_new
          rename_template: "{name}_{counter}{extension}"
```

and it works without problem... I deleted the `IMAGE` folder and created a new one but doesn't work. This is a mystery... will keep studying the problem.
