### ISSUE TITLE
«found character '%' that cannot start any token» when using {created.strftime('%Y-%m-%d')}

### ISSUE THREAD

**Issue by iburunat** [tfeldmann/organize#173]
Hi!
Just upgraded and was fixing my config, when I stumbled upon this error.

I was replacing the old:

```yaml
{created.year}-{created.month:02}-{created.day:02}/{created.year}-{created.month:02}-{created.day:02}.{extension.lower}
```

with

```yaml
{created.strftime('%Y-%m-%d')}/{created.strftime('%Y-%m-%d')}.{extension.lower}
```

This is the error:

```shell
ScannerError: while scanning for the next token
found character '%' that cannot start any token
  in "<unicode string>", line 20, column 82:
     ... oogle Photos/{created.strftime('%Y-%m-%d')}/{created.strftime('% ... 

```

Not sure what I am doing wrong.
This is the piece of config:

```yaml
  - locations: '/Users/user/Pictures/album/Google Photos'
    subfolders: false
    enabled: true
    filters:
      - created
      - extension:
          - jpg
          - png
    actions:
      - shell: |
#         some shell actions here
#         some shell actions here
#         some shell actions here
      - move: # and rename
          dest: '/Users/user/Pictures/album/Google Photos/{created.strftime('%Y-%m-%d')}/{created.strftime('%Y-%m-%d')}.{extension.lower}'
          on_conflict: rename_new
          rename_template: "{name}_{counter}{extension}"
```
