### ISSUE TITLE
[v2.0.8] Symbolic links are not detected by `filters.name.startswith`

### ISSUE THREAD

**Issue by andreoliwa** [tfeldmann/organize#178]
Rule:

```yaml
rules:
  - name: "Echo .bash files on the root"
    locations: ~/
    filters:
      - name:
          # TODO fix: Symbolic links are not detected by filters.name.startswith
          startswith: .bash
    actions:
      - echo: "{name}"
```

Output:

```
❯ organize run
organize 2.0.8
Config: "/Users/aa/Library/Application Support/organize/config.yaml"

⚙ Echo .bash files on the root ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
/Users/aa
  .bash_history
    - (echo) .bash_history
```

My root files (`.bash_history` is an actual file, the others are symlinks):

```
❯ ls -1 ~/.bash*
/Users/aa/.bash_history
/Users/aa/.bash_profile -> /Users/aa/dotfiles/roles/bash/files/.bash_profile.sh
/Users/aa/.bashrc -> /Users/aa/dotfiles/roles/bash/files/.bashrc.sh
```
