### ISSUE TITLE
Use the same `locations` options for a list of `path`s

### ISSUE THREAD

**Issue by andreoliwa** [tfeldmann/organize#179]
Given this rule (mentioned here: https://github.com/tfeldmann/organize/issues/174#issuecomment-1034073690)

```yaml
rules
  - name: "Delete .DS_Store"
    locations:
      - path: ~/Documents
        system_exclude_files: []
      - path: ~/Downloads/
        system_exclude_files: []
      - path: ~/Desktop/
        system_exclude_files: []
      - path: ~/Library/Mobile Documents/com~apple~QuickTimePlayerX/Documents
        system_exclude_files: []
      - path: ~/OneDrive/
        system_exclude_files: []
    subfolders: true
    filters:
      - name: .DS_Store
    actions:
      - trash
```

It would be nice to rewrite it as:

```yaml
slugify_folders: &slugify
  - ~/Documents
  - ~/Downloads/
  - ~/Desktop/
  - ~/Library/Mobile Documents/com~apple~QuickTimePlayerX/Documents
  - ~/OneDrive/

rules
  - name: "Delete .DS_Store"
    locations:
      - path: *slugify
        system_exclude_files: []
    subfolders: true
    filters:
      - name: .DS_Store
    actions:
      - trash
```

But I get a config error:

```
❯ organize sim
organize 2.0.8
Config: "/Users/aa/Library/Application Support/organize/config.yaml"
Error: Invalid config file!
'organize rule configuration' Key 'rules' error:
Key 'locations' error:
[{'path': ['~/Documents', '~/Downloads/', '~/Desktop/', '~/Library/Mobile Documents/com~apple~QuickTimePlayerX/Documents', '~/OneDrive/'], 'system_exclude_files': []}] should be instance of 'str'
{'path': ['~/Documents', '~/Downloads/', '~/Desktop/', '~/Library/Mobile Documents/com~apple~QuickTimePlayerX/Documents', '~/OneDrive/'], 'system_exclude_files': []} should be instance of 'str'
Key 'path' error:
['~/Documents', '~/Downloads/', '~/Desktop/', '~/Library/Mobile Documents/com~apple~QuickTimePlayerX/Documents', '~/OneDrive/'] should be instance of 'str'
```

I don't know if it's possible/easy, but it would be nice if `path` accepted a list as well (`str | List[str]`), in order to reuse other options.

---

This would also be useful to ignore errors for non-existent directories, writing `ignore_errors` only once:

```yaml
mobile_upload_folders: &mobile_upload
  - path: ~/OneDrive/Pictures/Camera Roll/
    ignore_errors: true
  - path: ~/OneDrive/Pictures/Download/
    ignore_errors: true
  - path: ~/OneDrive/Pictures/Facebook/
    ignore_errors: true
  - path: ~/OneDrive/Pictures/Screenshots/
    ignore_errors: true
  - path: ~/OneDrive/Pictures/Telegram/
    ignore_errors: true
  - path: ~/OneDrive/Pictures/WhatsApp Animated Gifs/
    ignore_errors: true
  - path: ~/OneDrive/Pictures/WhatsApp Images/
    ignore_errors: true
  - path: ~/OneDrive/Pictures/WhatsApp Video/
    ignore_errors: true
  - path: ~/OneDrive/Pictures/Samsung Gallery/
    ignore_errors: true
```

**Comment by xdhmoore** [comment]
Another benefit of this would be more flexibility in changing the location settings other than path for each use of the location alias:

```
slugify_folders: &slugify
  - ~/Documents
  - ~/Downloads/
  - ~/Desktop/
  - ~/Library/Mobile Documents/com~apple~QuickTimePlayerX/Documents
  - ~/OneDrive/

rules
  - name: "Delete a file"
    locations:
      - path: *slugify
    filters:
      - name: delete_me
    actions:
      - trash
      
  - name: "Move nested folder"
    target: dirs
    locations:
      - path: *slugify
        max_depth: 2                     # <--- different setting
    filters:
      - name: nested_folder
    actions:
      - move: dest_folder
``` 

Maybe there's a way to do this already, but I haven't found it.

**Comment by rickcecil** [comment]
I just encountered this error. I am trying to add exclude_dirs and exclude_files options to locations and to do that, AFAICT, I need to change it from 

`location: *alias`

to 

```
location:
  - path: /path/to.dir
     exclude_dirs: ["*._*"]
     exclude_files: ["*DS"]
```
The solution proposed by @andreoliwa is exactly how I thought it would work.

Thanks!
