### ISSUE TITLE
Filter "created" does not output date and time

### ISSUE THREAD

**Issue by wintuxx** [tfeldmann/organize#181]
Hello all,
In my config I try to rename the files with the filter "created" and move them to a certain folder.

Unfortunately, no values are output in the variables used.

VID-{created.year}{created.month}{created.day}.{created.hour}-{created.minutes}.{extension.lower}

VID-.-.<built-in method lower of str object at 0xb65aad00>

The file name should then look like this:
Example:
VID-20220210-06-20.mp4

here my config:
```
  - locations:
      - *downloads
    filters:
      - extension:
          - mp4
          - avi
          - mpeg
          - mpg
          - mov
          - mkv
          - flv
          - m4v
          - 3gp
          - wmv
      - name:
          case_sensitive: false
      - created
    actions:
      - move: '/srv/mergerfs/Pool/Videos/VID-{created.year}{created.month}{created.day}.{created.hour}-{created.minutes}.{extension.lower}'  
    subfolders: false
```
