### ISSUE TITLE
Filter duplicate: searchs subfolder in excluded folders

### ISSUE THREAD

**Issue by wintuxx** [tfeldmann/organize#183]
```
rules:
# verschiebe doppelte Dateien in den Ordner Duplicate
  - locations:
      - path: '/srv/mergerfs/Pool/'
        exclude_dirs: ['/srv/mergerfs/Pool/Backup/','/srv/mergerfs/Pool/Windows Backup/','/srv/mergerfs/Pool/Vault/','/srv/mergerfs/Pool/Steuer/','/srv/mergerfs/Pool/starmoney/','/srv/mergerfs/Pool/Treiber/','/srv/mergerfs/Pool/Duplicate/','/srv/mergerfs/Pool/Work/','/srv/mergerfs/Pool/ssd/','/srv/mergerfs/Pool/*/$RECYCLE.BIN','/srv/mergerfs/Pool/$RECYCLE.BIN']
    filters:
      - duplicate
      - extension
    actions:
      - move: '/srv/mergerfs/Pool/Duplicate/{extension.upper()}/'
    subfolders: true
```
Hello,
With the above config, I have the problem that it still searches the subfolders of the excluded folders for duplicates. This should not happen.

How do I prevent it from searching the subfolders of the excluded folders?

Many greetings 

wintux
