### ISSUE TITLE
Cannot ignore /Library in macOS

### ISSUE THREAD

**Issue by zeitchef** [tfeldmann/organize#187]
I've got a rule for delete `.DS_Store` files in all subdirectories from my user's home path `~/` carried over from organize v1. Unfortunately, when running the rule I get the following error:

`PermissionError: [Errno 1] Operation not permitted: b'/Users/scott/Library/Application Support/CallHistoryTransactions'`

Here is the ruleset in question:

```
  - name: 'Delete .DS_Store files'
    locations:
      - path: '~/'
        system_exclude_files: []
        system_exclude_dirs: ['~/Library']
    subfolders: true
    filters:
      - name: .DS_Store
    actions:
      - delete
```

What am I overlooking here? Thanks for the great update to `organize` - I use it everyday!
