### ISSUE TITLE
- (move) ERROR! path '' should be a directory

### ISSUE THREAD

**Issue by tordenflesk** [tfeldmann/organize#191]
- (move) Move to G:\FILENAME.mkv
    - (move) ERROR! path '' should be a directory

```
rules:
  - locations: \\SERVER\data01\tdarr\output
    name: Tdarr
    subfolders: true
    filters:
      - extension: mkv
      - lastmodified:
          minutes : 10
    actions:
      - move:
          dest: G:\
          on_conflict: rename_new
          rename_template: "{name}-{counter}{extension}"
```

organize, version 2.1.2, Python 3.8.6
