### ISSUE TITLE
Feature Request: rule.tags 

### ISSUE THREAD

**Issue by carpii** [tfeldmann/organize#199]
**Is your feature request related to a problem? Please describe.**

I'd like to keep all my rules in one file (easier to maintain, and you know they will be run sequentially)
I'd also like to run a subset of rules on occasion, rather than all of them, or likewise exclude certain groups of rules. 

**Describe the solution you'd like**
One solution would be to allow rules to have one or more 'tags'

````
  - name: "Test rule"
    locations:
      - ~/Downloads
    filters:
      - extension: pdf
    actions:
      - shell: '~/bin/organize-pdf-handler "{path}"'
    tags:
      - home
      - nas_mounted
````

Then you could run a subset of rules..

    organize run --include-tags home

Or exclude some

    organize run --exclude-tags nas_mounted

**Describe alternatives you've considered**
Maintaining seperate config files for the various scenarios. It would be complex and difficult to maintain, and probably require duplicated rules.

**Additional context**
I'd also like to explore hooking organize up to inotify, in which case it would be useful to handle an inotify event and then trigger just the revelant rules, without running the entire ruleset.

Great tool by the way, thanks
