### ISSUE TITLE
[Feature Request] Add glob-compatible syntax support to Folder section

### ISSUE THREAD

**Issue by mktums** [tfeldmann/organize#2]
Also, it'll be very nice to have `globstar` support, which is, I quote

> If set, the pattern ‘**’ used in a filename expansion context will match all files and zero or more directories and subdirectories. If the pattern is followed by a ‘/’, only directories and subdirectories match.

**Comment by tfeldmann** [comment]
I guess you want to use this to include subfolders in your rule?

You can use the `subfolders: true` setting to search a folder and all its subfolders as [documented here](http://organize.readthedocs.io/en/latest/page/config.html#rule-syntax):

```yaml
rules:
  - folders: ~/Downloads
    subfolders: true
    filters: ...
    actions: ...
```

With globstar support, you'd have two places to setup filters, so I decided against globstar support to keep the configuration simple and clean.
