### ISSUE TITLE
filecontent filter + rename action = multiple renames

### ISSUE THREAD

**Issue by drgrandios** [tfeldmann/organize#200]
I have the following rule running on a current version of organize (installed via pip):

```yaml
  # try to extract the first date from the file and rename it accordingly
  - name: date_rename
    locations: /scan/ocr
    filters:
      - name
      - extension: pdf
      - filecontent: '(?P<m>[0123]\d)\.(?P<d>[01]\d)\.(?P<y>[12][09]\d\d)'
    actions:
      - rename: "{filecontent.y}-{filecontent.m}-{filecontent.d}_{name}.pdf"
```
Unfortunately after "rename", the filter triggers on the renamed file again and starts the action over and over... it seems to run 5 times and then proceeds with the next rule:

```
scan/ocr
  20220401_173738.pdf
    - (rename) Rename to /scan/ocr/2022-23-03_20220401_173738.pdf
  2022-23-03_20220401_173738.pdf
    - (rename) Rename to /scan/ocr/2022-23-03_2022-23-03_20220401_173738.pdf
  2022-23-03_2022-23-03_20220401_173738.pdf
    - (rename) Rename to /scan/ocr/2022-23-03_2022-23-03_2022-23-03_20220401_173738.pdf
  2022-23-03_2022-23-03_2022-23-03_20220401_173738.pdf
    - (rename) Rename to /scan/ocr/2022-23-03_2022-23-03_2022-23-03_2022-23-03_20220401_173738.pdf
  2022-23-03_2022-23-03_2022-23-03_2022-23-03_20220401_173738.pdf
    - (rename) Rename to /scan/ocr/2022-23-03_2022-23-03_2022-23-03_2022-23-03_2022-23-03_20220401_173738.pdf
```

Is there a way to stop the rule from targeting the renamed file again?

**Comment by tfeldmann** [comment]
This is a bug and shouldn't happen.

**Comment by telometto** [comment]
I'm experiencing the same issue with the following:
```yml
rules:
  - name: "Renaming DVD folders"
    locations:
      - path: "/mnt/backups/DVDs"
        max_depth: null
    targets: dirs
    subfolders: true
    filters:
      - name:
          contains: "DVD"
    actions:
      - echo: "{path}"
      - rename:
          name: "{name.replace('[DVD] ','')}-{name.replace(' ', '_')}-{name.replace(' [1080p]','')}"
          on_conflict: "overwrite"
```

**Comment by tfeldmann** [comment]
@drgrandios Your issue seems like a bug where files are handled multiple times where they shouldn't. It's on my todo.

@telometto I replicated your issue and found this is more like a documentation issue 😅
What you're trying to do is this:

```yaml
    actions:
      - echo: "{path}"
      - rename:
          name: "{name | replace('[DVD] ','') | replace(' [1080p]','') | replace(' ', '_')}"
          on_conflict: "overwrite"
```

`{name.replace(sth, other)` takes the name and replaces `sth` with `other` but works from the full name every time. By using pipes as in the example above you can chain multiple renames.
