### ISSUE TITLE
Speed issue with v2, and issue with losing modified date/time.

### ISSUE THREAD

**Issue by Nurple** [tfeldmann/organize#203]
Heya,

I updated my config for v2 and noticed there's a big diffence in speed, what took a few seconds in v1 is taking minutes in v2, also the modified date/time gets changed to the current time.

I'm probably doing something wrong in my config.

**Expected behavior:**
Speed of task to be the same, and not have the modified date/time be changed to the current time.

**Environment:**

 - OS: Windows 10 - 21H2 - x64
 - Python Version: v3.10.3
 - Organize Version:  v2.1.2

**Your config file**

```yaml
rules:
  - locations: "D:/GoPro/"
    subfolders: true
    filters:
      - extension:
          - mp4
      - lastmodified
    actions:
      - move: "D:/GoPro Sorted/{lastmodified.strftime('%Y-%m-%d')}/"
```
