### ISSUE TITLE
Trigger global failure on shell error?

### ISSUE THREAD

**Issue by xdhmoore** [tfeldmann/organize#208]
**Is your feature request related to a problem? Please describe.**
Is there a way to trigger a global halt of the workflow when a particular (shell) action fails instead of continuing with other rules? I have some actions that apply to the whole source location and if they fail it doesn't make sense to go on. It doesn't do much harm though.

**Describe the solution you'd like**
Something like a `fail_globally` attribute on the shell action:
```
    actions: # TODO fail completely when this fails
      - shell:
          cmd: pwsh -C "Write-Error this should stop everything"
          ignore_errors: false
          # HERE: Causes the whole workflow to stop on failure if an error happens and ignore_errors==false
          fail_globally: true  
    
```

** Alternatives **
I'm hitting this because I have a rule that I want to run just once, so I use a filter to grab just the whole source folder as a way of executing the rule once. This is the rule I want to fail globally. I guess this is sort of a hack so maybe there's a better way.
