### ISSUE TITLE
Define a repo for rules

### ISSUE THREAD

**Issue by rafo** [tfeldmann/organize#217]
**Dont reinvent the wheel...**

...and let users contribute their rules to a separate repo / website.

**Solution**

- Define some rules (naming, file endings, utf-8, etc. pp)
- Gather some volunteers to check for malitious code.
- Create a website with search ,filters and ratings
- Profit ;D 

Possible match in your Roadmap https://github.com/tfeldmann/organize/projects/4#card-25088440

**Comment by tfeldmann** [comment]
Good idea. Creating a website for this is a bit too much but a folder with some predefined rules would certainly be useful and could live in this repository. Goes on the todo list.

**Comment by tfeldmann** [comment]
I'm having a hard time defining what these predefined rules might look like. Maybe something like snippets?
```yaml
description: "Filters images containing GPS information"
type: "filter"
---
- exif: gps.gpsdate
```

```yaml
description: "Recursively delete all empty directories"
type: "rule"
---
rules:
  - locations: "__placeholder__"
    targets: dirs
    subfolders: true
    filters:
      - empty
    actions:
      - delete
```

Any good ideas?

**Comment by carpii** [comment]
I haven't fully thought this through, but one idea might be to allow these standalone rules to be 'include'd into the main config, and you pass any required variables to it


So your generic 'blueprint' might be defined as..

````
description: "Recursively delete all empty directories"
type: "blueprint"
---
rules:
  - locations: "{{ vars.dir }}"
    targets: dirs
    subfolders: true
    filters:
      - empty
    actions:
      - delete
````

and then you include the blueprint from your main config like...

````
description: "Recursively delete all empty directories"
type: "rule"
include:
  file: blueprints/recursively_delete.yml
  vars:
    - dir: ~/Desktop/some_dir
````

It could then generate an error if `vars.dir` was not defined
