### ISSUE TITLE
Handle files and photos which are in a defined range of dates

### ISSUE THREAD

**Issue by rafo** [tfeldmann/organize#218]
**Is your feature request related to a problem? Please describe.**

I try to move pictures from one Holyday into one folder. I just need to know from which date till when my holyday took place.

**Describe the solution you'd like**

Add the strings `rangeCreated` `rangeModified` `exif`
 to the mode-[parameter](https://organize.readthedocs.io/en/latest/filters/#created) from the [created filter](https://organize.readthedocs.io/en/latest/filters/#created)

To define that you are searching for files created (modified == rangeModified) between e.g 2021-12-23 and 2021-12-26 and you want to move them in one folder, you could simply:

```
rules:
  - name: Christmas Wishlists
    locations: "~/Desktop"
    filters:
      - created:
          start: 2021-12-12
          end: 2021-12-20
          mode: rangeCreated
    actions:
      - move: "~/Lists/{created.start.year}/{name}-{created.start}-{created.end}/"
```

And for pictures, you could simply:

```
rules:
  - name: Christmas photos
    locations: "~/Desktop"
    filters:
      - created:
          start: 2021-12-23
          end: 2021-12-26
          mode: exif
    actions:
      - move: "~/Pictures/{created.start.year}/{name}-{created.start}-{created.end}/"
```

**Describe alternatives you've considered**
Maybe just use the python extension.

**Additional context**
[Pandas](http://pandas.pydata.org/) is great for time series in general, and has direct support for date ranges. For example [pd.date_range()](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.date_range.html). 

"Returns the range of equally spaced time points [...] such that they all satisfy start <[=] x <[=] end"

Maybe this could help?

**Comment by xdhmoore** [comment]
The following seems to work for me for last modified time using a python filter:

```

**Comment by xdhmoore** [comment]
The following seems to work for me for last modified time using a python filter:
```
#  organize run .\time_test.yaml --working-dir .

rules:
  - name: "test"
    locations: .
    filter_mode: all
    filters:
      - extension: "txt"
      - python: |
         import datetime
         start = datetime.datetime(2022, 6, 2 , 0, 0, 0).timestamp()
         end = datetime.datetime(2022, 6, 4 , 20, 42, 0).timestamp()

         return start < path.stat().st_mtime < end

    actions:
      - echo: "matched"

```
It looks like `st_ctime` [may work for creation time depending on your OS](https://docs.python.org/3/library/os.html#os.stat_result).

It also looks like this project already has Pillow as a dependency, so maybe extracting exif data in a filter [may not be much harder](https://www.thepythoncode.com/article/extracting-image-metadata-in-python).
