### ISSUE TITLE
Name option no longer works

### ISSUE THREAD

**Issue by zany130** [tfeldmann/organize#220]
**Describe the bug**
Name option no longer works

**Expected behavior**
check should pass with the name option set

**Environment (please complete the following information):**
 - OS: Garuda Linux 
 - Output of `organize --version`: organize, version 2.2.0

**Your config file**
```yaml
# organize configuration file
# https://organize.readthedocs.io

rules:
    - name: Scripts
    - locations:
          - path: ~/
      filters:
          - extension:
            - sh
      actions:
          - move: 
                dest: ~/Scripts/
```

**Log**
```
organize check
Checking: /home/zany130/.config/organize/config.yaml
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /usr/lib/python3.10/site-packages/schema.py:405 in validate                                      │
│                                                                                                  │
│   402 │   │   │   │   │   │   │   │   skey.handler(nkey, data, e)                                │
│   403 │   │   │   │   │   │   │   else:                                                          │
│   404 │   │   │   │   │   │   │   │   try:                                                       │
│ ❱ 405 │   │   │   │   │   │   │   │   │   nvalue = Schema(svalue, error=e, ignore_extra_keys=i   │
│   406 │   │   │   │   │   │   │   │   except SchemaError as x:                                   │
│   407 │   │   │   │   │   │   │   │   │   k = "Key '%s' error:" % nkey                           │
│   408 │   │   │   │   │   │   │   │   │   message = self._prepend_schema_name(k)                 │
│                                                                                                  │
│ /usr/lib/python3.10/site-packages/schema.py:366 in validate                                      │
│                                                                                                  │
│   363 │   │   if flavor == ITERABLE:                                                             │
│   364 │   │   │   data = Schema(type(s), error=e).validate(data, **kwargs)                       │
│   365 │   │   │   o = Or(*s, error=e, schema=Schema, ignore_extra_keys=i)                        │
│ ❱ 366 │   │   │   return type(data)(o.validate(d, **kwargs) for d in data)                       │
│   367 │   │   if flavor == DICT:                                                                 │
│   368 │   │   │   exitstack = ExitStack()                                                        │
│   369 │   │   │   data = Schema(dict, error=e).validate(data, **kwargs)                          │
│                                                                                                  │
│ /usr/lib/python3.10/site-packages/schema.py:366 in <genexpr>                                     │
│                                                                                                  │
│   363 │   │   if flavor == ITERABLE:                                                             │
│   364 │   │   │   data = Schema(type(s), error=e).validate(data, **kwargs)                       │
│   365 │   │   │   o = Or(*s, error=e, schema=Schema, ignore_extra_keys=i)                        │
│ ❱ 366 │   │   │   return type(data)(o.validate(d, **kwargs) for d in data)                       │
│   367 │   │   if flavor == DICT:                                                                 │
│   368 │   │   │   exitstack = ExitStack()                                                        │
│   369 │   │   │   data = Schema(dict, error=e).validate(data, **kwargs)                          │
│                                                                                                  │
│ /usr/lib/python3.10/site-packages/schema.py:167 in validate                                      │
│                                                                                                  │
│   164 │   │   │   except SchemaError as _x:                                                      │
│   165 │   │   │   │   autos += _x.autos                                                          │
│   166 │   │   │   │   errors += _x.errors                                                        │
│ ❱ 167 │   │   raise SchemaError(                                                                 │
│   168 │   │   │   ["%r did not validate %r" % (self, data)] + autos,                             │
│   169 │   │   │   [self._error.format(data) if self._error else None] + errors,                  │
│   170 │   │   )                                                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
SchemaError: Or({Optional('name'): <class 'str'>, Optional('enabled'): <class 'bool'>, Optional('subfolders'): <class 'bool'>, Optional('filter_mode'): Or('all', 'any', 'none'), Optional('tags'): Or(<class 'str'>,
[<class 'str'>]), Optional('targets'): Or('dirs', 'files'), 'locations': Or(<class 'str'>, [Or(<class 'str'>, {'path': And(<class 'str'>, <built-in function len>), Optional('max_depth'): Or(<class 'int'>, None),
Optional('search'): Or('depth', 'breadth'), Optional('exclude_files'): Or(<class 'str'>, [<class 'str'>]), Optional('exclude_dirs'): Or(<class 'str'>, [<class 'str'>]), Optional('system_exclude_files'): Or(<class
'str'>, [<class 'str'>]), Optional('system_exclude_dirs'): Or(<class 'str'>, [<class 'str'>]), Optional('filter'): Or(<class 'str'>, [<class 'str'>]), Optional('filter_dirs'): Or(<class 'str'>, [<class 'str'>]),
Optional('ignore_errors'): <class 'bool'>, Optional('filesystem'): <class 'object'>})]), Optional('filters'): [Optional(Or(Schema(Or('not created', 'created')), {Schema(Or('not created', 'created')):
{Optional('mode'): Or('older', 'newer'), Optional('years'): <class 'int'>, Optional('months'): <class 'int'>, Optional('weeks'): <class 'int'>, Optional('days'): <class 'int'>, Optional('hours'): <class 'int'>,
Optional('minutes'): <class 'int'>, Optional('seconds'): <class 'int'>}})), Optional(Or(Schema(Or('not date_added', 'date_added')), {Schema(Or('not date_added', 'date_added')): {Optional('mode'): Or('older',
'newer'), Optional('years'): <class 'int'>, Optional('months'): <class 'int'>, Optional('weeks'): <class 'int'>, Optional('days'): <class 'int'>, Optional('hours'): <class 'int'>, Optional('minutes'): <class
'int'>, Optional('seconds'): <class 'int'>}})), Optional(Or(Schema(Or('not duplicate', 'duplicate')), {Schema(Or('not duplicate', 'duplicate')): Or(<class 'str'>, [<class 'str'>], Schema({}))})),
Optional(Schema(Or('not empty', 'empty'))), Optional(Or(Schema(Or('not exif', 'exif')), {Schema(Or('not exif', 'exif')): Or(<class 'str'>, [<class 'str'>], Schema({}))})), Optional(Or(Schema(Or('not extension',
'extension')), {Schema(Or('not extension', 'extension')): Or(<class 'str'>, [<class 'str'>], Schema({}))})), Optional(Or(Schema(Or('not filecontent', 'filecontent')), {Schema(Or('not filecontent', 'filecontent')):
Or(<class 'str'>, [<class 'str'>], Schema({}))})), Optional(Or(Schema(Or('not hash', 'hash')), {Schema(Or('not hash', 'hash')): Or(<class 'str'>, [<class 'str'>], Schema({}))})), Optional(Or(Schema(Or('not name',
'name')), {Schema(Or('not name', 'name')): Or(<class 'str'>, {Optional('match'): <class 'str'>, Optional('startswith'): Or(<class 'str'>, [<class 'str'>]), Optional('contains'): Or(<class 'str'>, [<class 'str'>]),
Optional('endswith'): Or(<class 'str'>, [<class 'str'>]), Optional('case_sensitive'): <class 'bool'>})})), Optional(Or(Schema(Or('not size', 'size')), {Schema(Or('not size', 'size')): Or(<class 'object'>, [<class
'object'>])})), Optional(Or(Schema(Or('not lastmodified', 'lastmodified')), {Schema(Or('not lastmodified', 'lastmodified')): {Optional('mode'): Or('older', 'newer'), Optional('years'): <class 'int'>,
Optional('months'): <class 'int'>, Optional('weeks'): <class 'int'>, Optional('days'): <class 'int'>, Optional('hours'): <class 'int'>, Optional('minutes'): <class 'int'>, Optional('seconds'): <class 'int'>}})),
Optional(Or(Schema(Or('not mimetype', 'mimetype')), {Schema(Or('not mimetype', 'mimetype')): Or(<class 'str'>, [<class 'str'>], Schema({}))})), Optional({Schema(Or('not python', 'python')): Or(<class 'str'>,
{'code': <class 'str'>})}), Optional({Schema(Or('not regex', 'regex')): <class 'str'>})], 'actions': [Optional(Or('confirm', {'confirm': Or(<class 'str'>, {Optional('msg'): <class 'str'>, Optional('default'):
<class 'bool'>})})), Optional({'copy': Or(<class 'str'>, {'dest': <class 'str'>, Optional('on_conflict'): Or('skip', 'overwrite', 'trash', 'rename_new', 'rename_existing'), Optional('rename_template'): <class
'str'>, Optional('filesystem'): <class 'object'>})}), Optional('delete'), Optional({'echo': <class 'str'>}), Optional({'macos_tags': Or(<class 'str'>, [<class 'str'>])}), Optional({'move': Or(<class 'str'>,
{'dest': <class 'str'>, Optional('on_conflict'): Or('skip', 'overwrite', 'trash', 'rename_new', 'rename_existing'), Optional('rename_template'): <class 'str'>, Optional('filesystem'): <class 'object'>})}),
Optional({'python': Or(<class 'str'>, {'code': <class 'str'>, Optional('run_in_simulation'): <class 'bool'>})}), Optional({'rename': Or(<class 'str'>, {'name': <class 'str'>, Optional('on_conflict'): Or('skip',
'overwrite', 'trash', 'rename_new', 'rename_existing'), Optional('rename_template'): <class 'str'>})}), Optional({'shell': Or(<class 'str'>, {'cmd': <class 'str'>, Optional('run_in_simulation'): <class 'bool'>,
Optional('ignore_errors'): <class 'bool'>, Optional('simulation_output'): <class 'str'>, Optional('simulation_returncode'): <class 'int'>})}), Optional({'symlink': Or(<class 'str'>, [<class 'str'>], Schema({}))}),
Optional('trash')]}) did not validate {'name': 'Scripts'}
Missing keys: 'actions', 'locations'

During handling of the above exception, another exception occurred:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /usr/lib/python3.10/site-packages/organize/cli.py:254 in check                                   │
│                                                                                                  │
│   251 │   │   │   out.print("\n\n")                                                              │
│   252 │   │   │   out.rule("Schema validation", align="left")                                    │
│   253 │   │                                                                                      │
│ ❱ 254 │   │   validate(rules)                                                                    │
│   255 │   │                                                                                      │
│   256 │   │   if debug:                                                                          │
│   257 │   │   │   out.print("Validation ok.")                                                    │
│                                                                                                  │
│ /usr/lib/python3.10/site-packages/organize/config.py:103 in validate                             │
│                                                                                                  │
│   100                                                                                            │
│   101                                                                                            │
│   102 def validate(config: dict):                                                                │
│ ❱ 103 │   return CONFIG_SCHEMA.validate(config)                                                  │
│   104                                                                                            │
│                                                                                                  │
│ /usr/lib/python3.10/site-packages/schema.py:409 in validate                                      │
│                                                                                                  │
│   406 │   │   │   │   │   │   │   │   except SchemaError as x:                                   │
│   407 │   │   │   │   │   │   │   │   │   k = "Key '%s' error:" % nkey                           │
│   408 │   │   │   │   │   │   │   │   │   message = self._prepend_schema_name(k)                 │
│ ❱ 409 │   │   │   │   │   │   │   │   │   raise SchemaError([message] + x.autos, [e.format(dat   │
│   410 │   │   │   │   │   │   │   │   else:                                                      │
│   411 │   │   │   │   │   │   │   │   │   new[nkey] = nvalue                                     │
│   412 │   │   │   │   │   │   │   │   │   coverage.add(skey)                                     │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
SchemaError: 'organize rule configuration' Key 'rules' error:
Or({Optional('name'): <class 'str'>, Optional('enabled'): <class 'bool'>, Optional('subfolders'): <class 'bool'>, Optional('filter_mode'): Or('all', 'any', 'none'), Optional('tags'): Or(<class 'str'>, [<class
'str'>]), Optional('targets'): Or('dirs', 'files'), 'locations': Or(<class 'str'>, [Or(<class 'str'>, {'path': And(<class 'str'>, <built-in function len>), Optional('max_depth'): Or(<class 'int'>, None),
Optional('search'): Or('depth', 'breadth'), Optional('exclude_files'): Or(<class 'str'>, [<class 'str'>]), Optional('exclude_dirs'): Or(<class 'str'>, [<class 'str'>]), Optional('system_exclude_files'): Or(<class
'str'>, [<class 'str'>]), Optional('system_exclude_dirs'): Or(<class 'str'>, [<class 'str'>]), Optional('filter'): Or(<class 'str'>, [<class 'str'>]), Optional('filter_dirs'): Or(<class 'str'>, [<class 'str'>]),
Optional('ignore_errors'): <class 'bool'>, Optional('filesystem'): <class 'object'>})]), Optional('filters'): [Optional(Or(Schema(Or('not created', 'created')), {Schema(Or('not created', 'created')):
{Optional('mode'): Or('older', 'newer'), Optional('years'): <class 'int'>, Optional('months'): <class 'int'>, Optional('weeks'): <class 'int'>, Optional('days'): <class 'int'>, Optional('hours'): <class 'int'>,
Optional('minutes'): <class 'int'>, Optional('seconds'): <class 'int'>}})), Optional(Or(Schema(Or('not date_added', 'date_added')), {Schema(Or('not date_added', 'date_added')): {Optional('mode'): Or('older',
'newer'), Optional('years'): <class 'int'>, Optional('months'): <class 'int'>, Optional('weeks'): <class 'int'>, Optional('days'): <class 'int'>, Optional('hours'): <class 'int'>, Optional('minutes'): <class
'int'>, Optional('seconds'): <class 'int'>}})), Optional(Or(Schema(Or('not duplicate', 'duplicate')), {Schema(Or('not duplicate', 'duplicate')): Or(<class 'str'>, [<class 'str'>], Schema({}))})),
Optional(Schema(Or('not empty', 'empty'))), Optional(Or(Schema(Or('not exif', 'exif')), {Schema(Or('not exif', 'exif')): Or(<class 'str'>, [<class 'str'>], Schema({}))})), Optional(Or(Schema(Or('not extension',
'extension')), {Schema(Or('not extension', 'extension')): Or(<class 'str'>, [<class 'str'>], Schema({}))})), Optional(Or(Schema(Or('not filecontent', 'filecontent')), {Schema(Or('not filecontent', 'filecontent')):
Or(<class 'str'>, [<class 'str'>], Schema({}))})), Optional(Or(Schema(Or('not hash', 'hash')), {Schema(Or('not hash', 'hash')): Or(<class 'str'>, [<class 'str'>], Schema({}))})), Optional(Or(Schema(Or('not name',
'name')), {Schema(Or('not name', 'name')): Or(<class 'str'>, {Optional('match'): <class 'str'>, Optional('startswith'): Or(<class 'str'>, [<class 'str'>]), Optional('contains'): Or(<class 'str'>, [<class 'str'>]),
Optional('endswith'): Or(<class 'str'>, [<class 'str'>]), Optional('case_sensitive'): <class 'bool'>})})), Optional(Or(Schema(Or('not size', 'size')), {Schema(Or('not size', 'size')): Or(<class 'object'>, [<class
'object'>])})), Optional(Or(Schema(Or('not lastmodified', 'lastmodified')), {Schema(Or('not lastmodified', 'lastmodified')): {Optional('mode'): Or('older', 'newer'), Optional('years'): <class 'int'>,
Optional('months'): <class 'int'>, Optional('weeks'): <class 'int'>, Optional('days'): <class 'int'>, Optional('hours'): <class 'int'>, Optional('minutes'): <class 'int'>, Optional('seconds'): <class 'int'>}})),
Optional(Or(Schema(Or('not mimetype', 'mimetype')), {Schema(Or('not mimetype', 'mimetype')): Or(<class 'str'>, [<class 'str'>], Schema({}))})), Optional({Schema(Or('not python', 'python')): Or(<class 'str'>,
{'code': <class 'str'>})}), Optional({Schema(Or('not regex', 'regex')): <class 'str'>})], 'actions': [Optional(Or('confirm', {'confirm': Or(<class 'str'>, {Optional('msg'): <class 'str'>, Optional('default'):
<class 'bool'>})})), Optional({'copy': Or(<class 'str'>, {'dest': <class 'str'>, Optional('on_conflict'): Or('skip', 'overwrite', 'trash', 'rename_new', 'rename_existing'), Optional('rename_template'): <class
'str'>, Optional('filesystem'): <class 'object'>})}), Optional('delete'), Optional({'echo': <class 'str'>}), Optional({'macos_tags': Or(<class 'str'>, [<class 'str'>])}), Optional({'move': Or(<class 'str'>,
{'dest': <class 'str'>, Optional('on_conflict'): Or('skip', 'overwrite', 'trash', 'rename_new', 'rename_existing'), Optional('rename_template'): <class 'str'>, Optional('filesystem'): <class 'object'>})}),
Optional({'python': Or(<class 'str'>, {'code': <class 'str'>, Optional('run_in_simulation'): <class 'bool'>})}), Optional({'rename': Or(<class 'str'>, {'name': <class 'str'>, Optional('on_conflict'): Or('skip',
'overwrite', 'trash', 'rename_new', 'rename_existing'), Optional('rename_template'): <class 'str'>})}), Optional({'shell': Or(<class 'str'>, {'cmd': <class 'str'>, Optional('run_in_simulation'): <class 'bool'>,
Optional('ignore_errors'): <class 'bool'>, Optional('simulation_output'): <class 'str'>, Optional('simulation_returncode'): <class 'int'>})}), Optional({'symlink': Or(<class 'str'>, [<class 'str'>], Schema({}))}),
Optional('trash')]}) did not validate {'name': 'Scripts'}
Missing keys: 'actions', 'locations'
```

**Comment by xdhmoore** [comment]
In your example, you have an extra `-` in front of `locations`. Rules should have a list under it, and each list item is a set of key-value pairs. So the `-` in front of `name` denotes the first list item, an object, and `locations` is the second key-value pair under that same object.

**Comment by zany130** [comment]
this is the full config I am trying to get working I commented out name in the rules that are filtering files as names to test my theory but it is still failing 

```yaml
private_folders: &Pfolders
    - "pCloudDrive"
    - ".*"
    - "Applications"
    - "The Legend of Heroes Trails of Cold Steel III"

private_files: &Pfiles 
    - ".steampath"
    
rules:
#--------------------------------------------------------------------
    #- name: move screenshots into "Screenshots" folder
    - locations:
          - ~/Pictures/
      filters:
          - name:
                contains: "Screen"
                case_sensitive: false
      actions:
          - move: 
                dest: ~/Pictures/Screenshots/
                on_conflict: rename_new
                rename_template: "{name}-{counter}{extension}"
#--------------------------------------------------------------------

    # move Recordings into "Recordings" folder
    # name: Recordings
    - locations:
          - ~/Videos/
          - /mnt/GAMES/Videos/
      filters:
          - name:
                contains:
                  - "Record"
                  - "Replay"
                case_sensitive: false
      actions:
          - move:
                dest: /mnt/GAMES/Videos/Recordings/
                on_conflict: rename_new
                rename_template: "{name}-{counter}{extension}"
#--------------------------------------------------------------------

   - name: move Documents into documents folder
     locations:
          - path: ~/
            max_Depth: 1
            exclude_dirs: [*Pfolders]
            exclude_files: [*Pfiles]
      filters:
          - extension:
            - doc
            - docx
            - msg
            - odt
            - pages
            - wpd
            - wps
            - gddoc
            - ppt
            - pptx
            - xlr
            - xls
            - xlsx
            - pdf
            - mobi
      actions:
          - move: 
                dest: ~/Documents/
                on_conflict: rename_new
                rename_template: "{name}-{counter}{extension}"
#--------------------------------------------------------------------
 
   - name: move Log files into Logs folder
     locations:
          - path: ~/
            max_Depth: 1
            exclude_dirs: [*Pfolders]
            exclude_files: [*Pfiles]
      filters:
          - extension:
            - log
      actions:
          - move:
                dest: ~/Logs/
                on_conflict: rename_new
                rename_template: "{name}-{counter}{extension}"
#--------------------------------------------------------------------

   - name: Move applications into Applications folder
     locations:
        - path: ~/
          max_Depth: 1
          exclude_dirs: [*Pfolders]
          exclude_files: [*Pfiles]
      filters:
          - extension:
            - apk
            - app
            - exe
            - msi
            - jar
            - appimage
            - rpm
            - deb
            - pkg
            - .pkg.tar.xz
            - .pkg.tar.zst
      actions:
          - move:
                dest: ~/Applications/
                on_conflict: rename_new
                rename_template: "{name}-{counter}{extension}"

#--------------------------------------------------------------------

   - name: Move audio files into music folder
     locations:
          - path: ~/
            max_Depth: 1
            exclude_dirs: [*Pfolders]
            exclude_files: [*Pfiles]
      filters:
          - extension:
            - aif
            - iff
            - m3u
            - m4a
            - mid
            - mp3
            - mpa
            - wav
            - wma
      actions:
          - move:
                dest: ~/Music/
                on_conflict: rename_new
                rename_template: "{name}-{counter}{extension}"
#--------------------------------------------------------------------

   - name: Move video files into Videos
     locations:
          - path: ~/
            max_Depth: 1
            exclude_dirs: [*Pfolders]
            exclude_files: [*Pfiles]
      filters:
          - extension:
            - 3g2
            - 3gp
            - asf
            - avi
            - flv
            - m4v
            - mov
            - mp4
            - mpg
            - rm
            - srt
            - swf
            - vob
            - wmv
      actions:
          - move:
                dest: /mnt/GAMES/Videos/
                on_conflict: rename_new
                rename_template: "{name}-{counter}{extension}"
#--------------------------------------------------------------------

   - name: Move image files into Pictures
     locations:
          - path: ~/
            max_Depth: 1
            exclude_dirs: [*Pfolders]
            exclude_files: [*Pfiles]
      filters:
          - extension:
            - bmp
            - dds
            - gif
            - heic
            - jpg
            - png
            - psd
            - pspimage
            - tga
            - thm
            - tif
            - tiff
            - yuv
            - ai
            - eps
            - svg
      actions:
          - move: 
                dest: ~/Pictures/
                on_conflict: rename_new
                rename_template: "{name}-{counter}{extension}"
#--------------------------------------------------------------------

   - name: Move Archives into compressed folder
     locations:
          - ~/Downloads/
      filters:
          - extension:
            - tar
            - 7z
            - cbr
            - gz
            - rar
            - sitx
            - gz
            - zst
            - xz
            - zip
            - zipx
      actions:
          - move:
                dest: ~/Downloads/Compressed/
                on_conflict: rename_new
                rename_template: "{name}-{counter}{extension}"

#--------------------------------------------------------------------

   - name: Move Scripts into Scripts folder
     locations:
          - path: ~/
            max_Depth: 1
            exclude_dirs: [*Pfolders]
            exclude_files: [*Pfiles]
      filters:
          - extension:
            - sh
            - bat
            - vbs
      actions:
          - move: 
                dest: ~/Scripts/
                on_conflict: rename_new
                rename_template: "{name}-{counter}{extension}"
#--------------------------------------------------------------------

```

**Comment by xdhmoore** [comment]
I can't speak to the rest of your config, but I think the next error you posted is also caused by indentation. The `locations`  key needs to line up with the `name` above it. They are both keys of the same map object. I can reproduce it and when I make `locations`, `filters`, and `actions` line up with `name` above them, the error goes away. 

But in your next comment, your full config they look lined up correctly with the names as as far as I can tell. But I noticed that not all of your rules line up, or your locations & filters within a rule. Some of them are off by a space. I guess the theme here is that in YAML the indentation matters.

**Comment by zany130** [comment]
well this seems to work so i guess it wasn't a bug and it was a formatting issue
```
private_folders: &Pfolders
    - "pCloudDrive"
    - ".*"
    - "Applications"
    - "The Legend of Heroes Trails of Cold Steel III"

private_files: &Pfiles 
    - ".steampath"
    
rules:
#--------------------------------------------------------------------
    - name: move screenshots into "Screenshots" folder
      locations:
          - path : ~/Pictures/
            max_depth : 0
      filters:
          - name:
                contains: "Screen"
                case_sensitive: false
      actions:
          - move: 
                dest: ~/Pictures/Screenshots/
                on_conflict: rename_new
                rename_template: "{name}-{counter}{extension}"
#--------------------------------------------------------------------

    - name: move Recordings into "Recordings" folder
      locations:
          - ~/Videos/
          - /mnt/GAMES/Videos/
      filters:
          - name:
                contains:
                  - "Record"
                  - "Replay"
                case_sensitive: false
      actions:
          - move:
                dest: /mnt/GAMES/Videos/Recordings/
                on_conflict: rename_new
                rename_template: "{name}-{counter}{extension}"
#--------------------------------------------------------------------

    - name: move Documents into documents folder
      locations:
          - path: ~/
            max_Depth: 1
            exclude_dirs: [*Pfolders]
            exclude_files: [*Pfiles]
      filters:
          - extension:
            - doc
            - docx
            - msg
            - odt
            - pages
            - wpd
            - wps
            - gddoc
            - ppt
            - pptx
            - xlr
            - xls
            - xlsx
            - pdf
            - mobi
      actions:
          - move: 
                dest: ~/Documents/
                on_conflict: rename_new
                rename_template: "{name}-{counter}{extension}"
#--------------------------------------------------------------------
 
    - name: move Log files into Logs folder
      locations:
          - path: ~/
            max_Depth: 1
            exclude_dirs: [*Pfolders]
            exclude_files: [*Pfiles]
      filters:
          - extension:
            - log
      actions:
          - move:
                dest: ~/Logs/
                on_conflict: rename_new
                rename_template: "{name}-{counter}{extension}"
#--------------------------------------------------------------------

    - name: Move applications into Applications folder
      locations:
        - path: ~/
          max_Depth: 2
          exclude_dirs: [*Pfolders]
          exclude_files: [*Pfiles]
      filters:
          - extension:
            - apk
            - app
            - exe
            - msi
            - jar
            - appimage
            - rpm
            - deb
            - pkg
            - .pkg.tar.xz
            - .pkg.tar.zst
      actions:
          - move:
                dest: ~/Applications/
                on_conflict: rename_new
                rename_template: "{name}-{counter}{extension}"

#--------------------------------------------------------------------

    - name: Move audio files into music folder
      locations:
          - path: ~/
            max_Depth: 1
            exclude_dirs: [*Pfolders]
            exclude_files: [*Pfiles]
      filters:
          - extension:
            - aif
            - iff
            - m3u
            - m4a
            - mid
            - mp3
            - mpa
            - wav
            - wma
      actions:
          - move:
                dest: ~/Music/
                on_conflict: rename_new
                rename_template: "{name}-{counter}{extension}"
#--------------------------------------------------------------------

    - name: Move video files into Videos
      locations:
          - path: ~/
            max_Depth: 1
            exclude_dirs: [*Pfolders]
            exclude_files: [*Pfiles]
      filters:
          - extension:
            - 3g2
            - 3gp
            - asf
            - avi
            - flv
            - m4v
            - mov
            - mp4
            - mpg
            - rm
            - srt
            - swf
            - vob
            - wmv
      actions:
          - move:
                dest: /mnt/GAMES/Videos/
                on_conflict: rename_new
                rename_template: "{name}-{counter}{extension}"
#--------------------------------------------------------------------

      name: Move image files into Pictures
      locations:
          - path: ~/
            max_Depth: 1
            exclude_dirs: [*Pfolders]
            exclude_files: [*Pfiles]
      filters:
          - extension:
            - bmp
            - dds
            - gif
            - heic
            - jpg
            - png
            - psd
            - pspimage
            - tga
            - thm
            - tif
            - tiff
            - yuv
            - ai
            - eps
            - svg
      actions:
          - move: 
                dest: ~/Pictures/
                on_conflict: rename_new
                rename_template: "{name}-{counter}{extension}"
#--------------------------------------------------------------------

    - name: Move Archives into compressed folder
      locations:
          - ~/Downloads/
      filters:
          - extension:
            - tar
            - 7z
            - cbr
            - gz
            - rar
            - sitx
            - gz
            - zst
            - xz
            - zip
            - zipx
      actions:
          - move:
                dest: ~/Downloads/Compressed/
                on_conflict: rename_new
                rename_template: "{name}-{counter}{extension}"

#--------------------------------------------------------------------

    - name: Move Scripts into Scripts folder
      locations:
          - path: ~/
            max_Depth: 1
            exclude_dirs: [*Pfolders]
            exclude_files: [*Pfiles]
      filters:
          - extension:
            - sh
            - bat
            - vbs
      actions:
          - move: 
                dest: ~/Scripts/
                on_conflict: rename_new
                rename_template: "{name}-{counter}{extension}"
#--------------------------------------------------------------------

```
