### ISSUE TITLE
Add filter: macos_tags

### ISSUE THREAD

**Issue by elsatch** [tfeldmann/organize#227]
**Is your feature request related to a problem? Please describe.**
I use to tag my invoices with macOS tags, like "2022Q3" and "Invoice". I leave them on Downloads folder and collect them quarterly. I was checking the filter rules for macos_tags, but discovered that tags are only available as actions.

**Describe the solution you'd like**
In the same vein as the macos_tags action, I would love to have a macos_tags filter to find the files tagged with certain tags (single tag or list of tags).

**Describe alternatives you've considered**
I have checked the macos_tags python library site (which I assume is the one being used by organize), and it implements a macos_tags.find() method. I wondered if I could scratch some custom Python filter to find them, but I am not sure given I would need to side load the library every time I run the program.

**Comment by elsatch** [comment]
I have explored the Python filter route, but I might be reading the documentation wrong!

In Python interactive shell, I tried:

```
>>> import macos_tags
>>> macos_tags.find('Invoices')
['/Users/elsatch/Downloads/namecheap-order-994581234.pdf']
```

Then I tried replicating the result with a rule (at invoices.yml):

```yaml
rules:
  - name: "Move invoices in my Download folder to a 20xxQx subfolder _Outbox"
    subfolders: true
    locations:
      - path: "~/Downloads/"
    filters:
      - python: |
          import macos_tags
          return macos_tags.find('Invoices')
    actions:
      - echo: "Found an invoice to move {path.name}"
    #  - copy: "~/_Outbox/Invoices/"
```

When I `organize sim`this rule, I get the list of all files in the folder, instead of the filtered results.
