### ISSUE TITLE
Renaming files omits the filename itself

### ISSUE THREAD

**Issue by telometto** [tfeldmann/organize#231]
**Describe the bug**
It seems that using `rename: "{name}.{extension.lower()}"` does not include the file name upon renaming. I have only run it in simulation mode so far, so I do not know if this is the issue if you do a proper run. I'm too afraid to test it, to be honest.

**Expected behavior**
The filename should be included in when the file is renamed.

**Screenshots**
![Screenshot from 2022-08-07 01-35-03](https://user-images.githubusercontent.com/65364211/183269071-69aaf618-d71b-4c0c-94e4-f008f676699e.png)

**Environment (please complete the following information):**
 - OS: Fedora 36
 - Output of `organize --version`: organize, version 2.3.0 (run in a venv)

**Your config file**
```yaml
# vars
home_folders: &home
  - $HOME/Documents
  - $HOME/Downloads
  - $HOME/Music
  - $HOME/Pictures

excl_dirs: &excl_priv
  - ".*"
  - "from_git"
  - "venv"

images: &img
  - jpg
  - jpeg
  - webp
  - png
  - gif

documents: &doc
  - odt
  - xls
  - xlsx
  - doc
  - docx
  - ods
  - odt
  - pdf
  - txt

videos: &vid
  - webm
  - mkv
  - mpv
  - mp4
  - mov

sound: &snd
  - mp3
  - ogg
  - m4a
  - wav

compressed: &comp
  - 7z
  - 7zip
  - zip
  - rar
  - gz
  - tar

garbage: &garbage
  - url
  - kdb
  - xml
  - nomedia

all_files: &all
  - *img
  - *doc
  - *vid
  - *comp
  - *snd

home_server: &hserv
  - /mnt/backups
  - /mnt/backups/backups
  - /mnt/backups/backups/documents
  - /mnt/backups/backups/downloads
  - /mnt/backups/backups/music
  - /mnt/backups/backups/pictures
  - /mnt/backups/backups/videos

rules:
  ### DESKTOP
  # rules for docs
  - name: "Finding documents in home dir"
    locations: *home
    subfolders: false
    filters:
      - extension: *doc
      - created
    actions:
      - echo: "Found {extension} in {path}!"
      - move: "$HOME/Documents/unsorted_docs/{extension.lower()}/{created.strftime('%Y-%m-%d')}/"
      - rename: "{name}.{extension.lower()}"

  # rules for img
  - name: "Finding images in home dir"
    locations: *home
    subfolders: false
    filters:
      - extension: *img
      - created
    actions:
      - echo: "Found {extension} in {path}!"
      - move: "$HOME/Pictures/unsorted_imgs/{extension.lower()}/{created.strftime('%Y-%m-%d')}/"
      - rename: "{name}.{extension.lower()}"

  # rules for videos
  - name: "Finding videos in home dir"
    locations: *home
    subfolders: false
    filters:
      - extension: *vid
      - created
    actions:
      - echo: "Found {extension} in {path}!"
      - move: "$HOME/Videos/unsorted_vids/{extension.lower()}/{created.strftime('%Y-%m-%d')}/"
      - rename: "{name}.{extension.lower()}"

  # rules for scripts
  - name: "Finding scripts in home dir"
    locations: *home
    subfolders: false
    filters:
      - extension: sh
      - created
    actions:
      - echo: "Found {extension} in {path}!"
      - move: "$HOME/Documents/unsorted_scripts/{extension.lower()}/{created.strftime('%Y-%m-%d')}/"
      - rename: "{name}.{extension.lower()}"

  # rules for sound files
  - name: "Finding sound files in home dir"
    locations: *home
    subfolders: false
    filters:
      - extension: *snd
      - created
    actions:
      - echo: "Found {extension} in {path}!"
      - move: "$HOME/Music/unsorted_music/{extension.lower()}/{created.strftime('%Y-%m-%d')}/"
      - rename: "{name}.{extension.lower()}"

  ### HOME SERVER
  # rules for docs
  - name: "Finding documents in home server dir"
    locations: *hserv
    subfolders: false
    filters:
      - extension: *doc
      - created
    actions:
      - echo: "Found {extension} in {path}!"
      - move: "/mnt/backups/backups/documents/unsorted_docs/{extension.lower()}/{created.strftime('%Y-%m-%d')}/"
      - rename: "{name}.{extension.lower()}"

  # rules for img
  - name: "Finding images in home server dir"
    locations: *hserv
    subfolders: false
    filters:
      - extension: *img
      - created
    actions:
      - echo: "Found {extension} in {path}!"
      - move: "/mnt/backups/backups/pictures/unsorted_imgs/{extension.lower()}/{created.strftime('%Y-%m-%d')}/"
      - rename: "{name}.{extension.lower()}"

  # rules for videos
  - name: "Finding videos in home server dir"
    locations: *hserv
    subfolders: false
    filters:
      - extension: *vid
      - created
    actions:
      - echo: "Found {extension} in {path}!"
      - move: "/mnt/backups/backups/videos/unsorted_vids/{extension.lower()}/{created.strftime('%Y-%m-%d')}/"
      - rename: "{name}.{extension.lower()}"

  # rules for scripts
  - name: "Finding scripts in home server dir"
    locations: *hserv
    subfolders: false
    filters:
      - extension: sh
      - created
    actions:
      - echo: "Found {extension} in {path}!"
      - move: "$HOME/Documents/unsorted_scripts/{extension.lower()}/{created.strftime('%Y-%m-%d')}/"
      - rename: "{name}.{extension.lower()}"

  # rules for sound files
  - name: "Finding sound files in home server dir"
    locations: *hserv
    subfolders: false
    filters:
      - extension: *snd
      - created
    actions:
      - echo: "Found {extension} in {path}!"
      - move: "/mnt/backups/backups/music/unsorted_music/{extension.lower()}/{created.strftime('%Y-%m-%d')}/"
      - rename: "{name}.{extension.lower()}"
```
**PS:** I'd like to substitute spaces in files with underscores (`_`) if such files are found - is this possible? I didn't want to open a new issue just to ask this. Thanks 😊

**Comment by tfeldmann** [comment]
For your first question (rename bug):

You forgot to add the `name` filter. Working example:
```yaml
rules:
  - locations: ~/Desktop
    filters:
      - name
      - extension
    actions:
      - rename:
          name: "{name}.{extension.lower()}"
          on_conflict: "overwrite"
```

Second question (How to replace spaces with underscores):

Working example:

```yaml
rules:
  - locations: ~/Desktop
    filters:
      - name
      - extension
    actions:
      - rename:
          name: "{name.replace(' ', '_')}.{extension.lower()}"
          on_conflict: "overwrite"
```
