### ISSUE TITLE
Way to operate on folders instead of files?

### ISSUE THREAD

**Issue by mope1** [tfeldmann/organize#25]
Hi! First of all, I'm very happy `organize` exists and and eager to contribute some features that I personally need. if you prefer to keep this project sweet and simple that is fine too of course!

 Anyways, here I go with another feature request that I will attempt to build. 

Consider the following use case:
```
# move stale projects to archive
  - subfolders: true
    folders:
      - '~/projects/'
    filters:
      - LastModified:
          days: 90
          mode: older
    actions: 
      - Move: /mnt/raid/archive-projects/{relative_path}
    subfolders: true
```

This technically works but has the following downsides:

- Files trickle over depending on their individual LastModified date. The level of annoyance from this depends on the nature of your projects.
- Empty folder structure gets left behind. I feel like removing empty folders should definitely be a something organize can do.

Hazel has a feature to match folders specifically (see screenshot below). Another valid value for the `Kind` field is `Music`, which switches the list of available filters to ones applicable to music files or any kind as well as generic ones. 
![screenshot_2018-11-20_12-55-43](https://user-images.githubusercontent.com/13020250/48772116-ad980880-ecc3-11e8-8473-9a47b7ecc126.png)

Now in the case of `organize`, I would suggest adding one relatively simple flag to the rule that will make the rule target folders only instead of files only:

```
# move stale projects to archive
rules:
  - target_folders: true
    folders:
      - '~/projects/'
    filters:
    - LastModified:
        days: 90
        mode: newer
    actions: 
      - Move: /mnt/raid/archive-projects/{relative_path}
```
By adding 3 lines of code https://github.com/mope1/organize/commit/8bcfe3502e984f11d6799da475072d0098d3d9bd the flag can be implemented and it already works with `LastModified` filter and `Move` action without further changes.

Now obviously some filters and actions might be more tricky, but imho if you defaulted the filter class to never match folders (or maybe error out if not implemented) when applied to folders, this feature would be quite useful. I could imagine e.g. a filter called `Empty` that works on both files and folders as well. 

**UPDATE** Turns out i'm less clever than i tought, as modifiying a file does not update the parent directory's DateModified, only the creation of new files. Therefore, more extensive changes would have to be made to the filters.
