### ISSUE TITLE
Python filter: regex.mon triggers error 'dict' object has no attribute 'mon'

### ISSUE THREAD

**Issue by christophberger** [tfeldmann/organize#252]
**Describe the bug**
I tried to write a python filter that takes a short month name and returns the corresponding month number. I took the python filter example from the docs that changes the last name into an email, and changed it as needed (see below)

### Issue

The preceding `regex` filter creates a `mon` attribute.
Python should be able to fetch that attribute as

```python
regex.mon
```

but I get an error instead: `(python) ERROR! 'dict' object has no attribute 'mon'`
When I change the code as follows:

```python
regex["mon"]
```

the code works.

- OS: macOS 12.6
- Output of `organize --version`: organize, version 2.2.0
- Python 3.10.8

**Your config file**

```YAML
  - name: "Monthly Hours"
    tags:
      - finances
    locations:
      - ~/Downloads
    filters:
      - extension: csv
      - regex: 'Monthly_Hours_(?P<year>\d\d\d\d)-(?P<mon>...)'
      - python: |
          print(regex)
          print(regex["year"])
          print(regex.mon)  # <- This syntax errors out
          months = {
            "Jan": "01",
            "Feb": "02",
            "Mar": "03",
            "Apr": "04",
            "May": "05",
            "Jun": "06",
            "Jul": "07",
            "Aug": "08",
            "Sep": "09",
            "Oct": "10",
            "Nov": "11",
            "Dec": "12",
          }
          return {"month": months[regex["mon"]]}
    actions:
      - move: "target_dir/Monthly_Hours_{regex.year}-{python.month}.csv"
```

Output of `organize sim`:
```
  Monthly_Hours_2022-Jan-01-2022-Jan-31.csv
    - (python) {'year': '2022', 'mon': 'Jan'}
    - (python) 2022
    - (python) ERROR! 'dict' object has no attribute 'mon'
```
