### ISSUE TITLE
A rule that includes both an include and an exclude filter ?

### ISSUE THREAD

**Issue by nodecentral** [tfeldmann/organize#279]
Hi, 

I can’t seem to get this to work, so assuming it might not be possible..

Can you use both include and exclude filters in the same rule, for example I just want `Men’s Health` not `Men’s Mental Health` - my config is below

````
  - name: "Find Men's Health Magazines"
    locations:
      - /Publications/TBS/
    subfolders: true
    filters:
      - Extension:
        - pdf
        #- jpg
      - name:
          startswith:
            - Men
          contains:
            - Health
          case_sensitive: false
       - not name:
          contains:
            - Mental
    actions:
      - echo: "{path} is a Men's Health magazine"
````

I’m using v2.40 via Docker.

**Comment by nodecentral** [comment]
Or is there a better way to do this sort of thing ?

**Comment by kamuridesu** [comment]
You can use Regex: https://organize.readthedocs.io/en/latest/filters/#regex
Or filter it using Python: https://organize.readthedocs.io/en/latest/filters/#python

**Comment by tfeldmann** [comment]
@nodecentral Your example works perfectly here. You got a small indentation error ("not name" is indented one space to far) maybe that's the problem.

Fixed config:
```yaml
rules:
  - name: "Find Men's Health Magazines"
    locations:
      - .
    subfolders: true
    filters:
      - name:
          startswith:
            - Men
          contains:
            - Health
          case_sensitive: false
      - not name:
          contains:
            - Mental
    actions:
      - echo: "{path} is a Men's Health magazine"

```
