### ISSUE TITLE
MacOS and .app folders

### ISSUE THREAD

**Issue by eimfach** [tfeldmann/organize#281]
**Is your feature request related to a problem? Please describe.**
MacOS has `.app` folders that are directories and executables at the same time (same for `.workflow`). With organize-tool I did not find a way to target these. Filter `extension` does only work for single files not dirs. `endswith` not work also.

**Describe the solution you'd like**
Maybe add support for filtering directories with extension e.g. `.app`

**Comment by kamuridesu** [comment]
I can successfully match `.app` with the following config:

```yaml
rules:
  - targets: dirs
    locations: "/test"
    subfolders: true
    filters:
    - name:
        endswith: .app
    actions:
      - echo: "{path.name}"
```
