### ISSUE TITLE
Shortcuts not registering?

### ISSUE THREAD

**Issue by xPandaemonium** [tfeldmann/organize#30]
This is an odd one because it seems to be inconsistent. I'm pointing the application to my desktop and asking it to move new .lnk files (shortcuts) somewhere else in my home directory... While it has worked before it often ignores certain shortcuts as if they don't even exist.

Edit
It managed to recognize the "ImageMagick Display" applications shortcut when updating it but I see no discernible difference between "it" and other shortcuts that sit on my desktop.

**Comment by tfeldmann** [comment]
Sorry for my late reply. That is indeed odd. Can you post your full config file here? And could you paste the output of the `dir` command of your desktop?

**Comment by DaemonPhoenix42** [comment]
No worries!
honestly IDK what's up with it, trying to replicate yields me no issues; yet there were specific shortcuts that refused to get recognized by the script and I can't for the life of me recreate it, so maybe a fluke?
I even tried dumping all my icons to check.

It did happen after installing a new application so I'm not sure if that's a contributing factor.

I'll keep trying and make an update if I find an offending shortcut.lnk

Config
---

```
rules:
  # ------------------------------------------------------------------
  # # """ Move screenshots into 'Screenshots' folder """
  # - folders:
  #     - ~/Desktop
  #   filters:
  #     - Filename:
  #         startswith: 'Screen Shot'
  #   actions:
  #     - Move:
  #         dest: ~/Desktop/Screenshots/
  # ------------------------------------------------------------------
  # # """ Move incomplete downloads older > 30 days into the trash """
  # - folders:
  #     - ~/Downloads
  #   filters:
  #     - Extension:
  #         - download
  #         - crdownload
  #         - part
  #     - LastModified:
  #         days: 30
  #         mode: older
  #   actions:
  #     - Trash
  # ------------------------------------------------------------------
  # # """ Move Media into 'dump' folder """
  - folders: 
    - ~/Desktop
    - ~/Downloads
    filters:
      - Extension:
        - png
        - jpg
        - jpeg
        - webp
        - ico
        - tif
        - bmp
        - svg
        - gif
        - mkv
        - mp4
        - webm
        - wmv
        - gifv
        - avi
        - mov
        - mp3
        - wav
        - ogg
    actions:
      - Move:
          dest: '~/!Dump/Media/'
  # ------------------------------------------------------------------
  # # """ Move Media into 'dump' folder """
  - folders: 
    - ~/!Dump/Media
    filters:
      - Extension:
        - png
        - jpg
        - jpeg
        - webp
        - ico
        - tif
        - bmp
        - svg
        - gif
    actions:
      - Move:
          dest: '~/!Dump/Media/Images/'
  # ------------------------------------------------------------------
  # # """ Move Media into 'dump' folder """
  - folders: 
    - ~/!Dump/Media/Images
    filters:
      - Extension:
        - ico
    actions:
      - Move:
          dest: '~/!Dump/Media/Images/Icons/'
  # ------------------------------------------------------------------
  # # """ Move Media into 'dump' folder """
  - folders: 
    - ~/!Dump/Media
    filters:
      - Extension:
        - gifv
        - mov
        - mkv
        - mp4
        - webm
        - wmv
        - avi
    actions:
      - Move:
          dest: '~/!Dump/Media/Video/'
  # ------------------------------------------------------------------
  # # """ Move Media into 'dump' folder """
  - folders: 
    - ~/!Dump/Media
    filters:
      - Extension:
        - mp3
        - wav
        - ogg
    actions:
      - Move:
          dest: '~/!Dump/Media/Audio/'
  # ------------------------------------------------------------------
  # # """ Move example/referance notes into 'documents' folder """
  # - folders: 
  #   - ~/Desktop
  #   - ~/Downloads
  #   filters:
  #     - Filename:
  #       contains: ('AHK', 'AutoHotkey', 'Example', 'Reference', 'Template', 'Custom', 'Config')
  #       case_sensitive: false
  #   actions:
  #     - Move:
  #         dest: '~/!Dump/Documents/'
  # ------------------------------------------------------------------
  # # """ Move desktop shortcuts into 'links' folder """
  - folders: 
    - ~/Desktop
    filters:
      - Extension:
        - lnk
    actions:
      - Move:
          dest: '~/Links/'
          overwrite: true
  # ------------------------------------------------------------------
  # # """ Move Bookmark files into 'Link' folder """
  - folders: 
    - ~/Desktop
    - ~/Downloads
    filters:
      - Extension:
        - url
    actions:
      - Move:
          dest: '~/!Dump/Bookmarks/Universal Resorce Links/'
          overwrite: true
  # ------------------------------------------------------------------
  # # """ Move AutoHotkey files into 'dump' folder """
  - folders: 
    - ~/Desktop
    - ~/Downloads
    filters:
      - Extension:
        - ahk
    actions:
      - Move:
          dest: '~/!Dump/Code/AutoHotkey/'
  # ------------------------------------------------------------------
  # # """ Move Powershell files into 'dump' folder """
  - folders: 
    - ~/Desktop
    - ~/Downloads
    filters:
      - Extension:
        - ps1
    actions:
      - Move:
          dest: '~/!Dump/Code/Powershell/'
  # ------------------------------------------------------------------
  # # """ Move batch files into 'dump' folder """
  - folders: 
    - ~/Desktop
    - ~/Downloads
    filters:
      - Extension:
        - bat
        - cmd
    actions:
      - Move:
          dest: '~/!Dump/Code/Batch/'
  # ------------------------------------------------------------------
  # # """ Move VBScript  files into 'dump' folder """
  - folders: 
    - ~/Desktop
    - ~/Downloads
    filters:
      - Extension:
        - vbs
    actions:
      - Move:
          dest: '~/!Dump/Code/VBScript/'
  # ------------------------------------------------------------------
    # # """ Move registry files into 'dump' folder """
  - folders: 
    - ~/Desktop
    - ~/Downloads
    filters:
      - Extension:
        - reg
    actions:
      - Move:
          dest: '~/!Dump/Code/Regedit/'
  # ------------------------------------------------------------------
  # # """ Move Desktop notes into 'dump' folder """
  - folders: 
    - ~/Desktop
    - ~/Downloads
    filters:
      - Extension:
        - txt
        - pdf
        - docx
        - csv
    actions:
      - Move:
          dest: '~/!Dump/Documents/'
  # ------------------------------------------------------------------
  # # """ Move archives into 'dump' folder """
  - folders: 
    - ~/Desktop
    - ~/Downloads
    filters:
      - Extension:
        - zip
        - rar
        - tgz
        - 7z
    actions:
      - Move:
          dest: '~/!Dump/Archives/'
  # ------------------------------------------------------------------
  - folders: 
    - ~/Desktop
    - ~/Downloads
    filters:
      - Extension:
        - exe
        - msi
    actions:
      - Move:
          dest: '~/!Dump/Utilities/'
  # ------------------------------------------------------------------
  - folders: 
    - ~/Desktop
    - ~/Downloads
    filters:
      - Extension:
        - apk
    actions:
      - Move:
          dest: '~/!Dump/Android/Applications/'
  # ------------------------------------------------------------------
  - folders: 
    - ~/Desktop
    - ~/Downloads
    filters:
      - Extension:
        - py
        - pyw
    actions:
      - Move:
          dest: '~/!Dump/Code/Python/'
  # ------------------------------------------------------------------
  # # """ Move downloaded blender files into 'dump' folder """
  - folders: 
    - ~/Desktop
    - ~/Downloads
    filters:
      - Extension: 
        - blend
    actions:
      - Move:
          dest: '~/!Dump/Blender/'
          overwrite: true
  # ------------------------------------------------------------------
```

Haven't taken enough time to figure out a better solution to this, as I have to run the command a couple of times to make sure things all end up where they should

**Comment by tfeldmann** [comment]
Hi, any updates on this? Did you try it with the newly released version?

**Comment by DaemonPhoenix42** [comment]
I was unaware you released an update, thank you I'll check it out. 

As I said it's been inconsistent and in fact a rarity at that given how often I use your code. Running the simulation it has no problem identifying the shortcuts that currently reside on my desktop. I was only able to spot the issue once more after installing some software and attempting to organize the shortcut it automatically place on the desktop. At which point I just decided to move it manually. From where I stand it does not seem like an easy thing to pin down.

**Comment by tfeldmann** [comment]
I just found out that shortcuts inside the hidden folders `C:\Users\Public\Desktop` and `C:\All Users\Public\Desktop` show up on your desktop, too.

So I guess the applications put their shortcuts there and organize could not find them because it only searches the user's desktop (`~/Desktop`) as defined in the config file.

So in order to find everything shown on the desktop you can do something like this:

```yaml
desktop_locations: &desktops
  - "%public%/Desktop"
  - "~/Desktop"

rules:
  - folders:
      - *desktops
      - "~/Downloads"
    actions:
      - Echo: "Detected file: {path} "
```

I just released version 1.5.2 to support the `%public%`-variable. Please update before trying this script!
