### ISSUE TITLE
filecontent is not working / empty

### ISSUE THREAD

**Issue by jl54** [tfeldmann/organize#322]
**Describe the bug**
I'm trying to work with the filecontent filter, but it doesn't seem to work.
I configured the example rule from the [docs](https://organize.readthedocs.io/en/latest/filters/#filecontent) to show the content for a PDF.
The `oranize run` command just outputs "Nothing to do."
The content of the test PDF I use is searchable.

Am I doing something wrong?

**Screenshots**
![Screenshot 2023-10-14 133009](https://github.com/tfeldmann/organize/assets/11390727/b8f65dba-7293-4a53-9342-d194c70992b0)

**Environment**

- OS: Windows 11 Home (22H2)
- Output of `organize --version`: organize, version 2.4.2
- Tested Python Versions: 3.8.10 & 3.10.5 

**Your config file**

```yaml
# organize configuration file
# https://organize.readthedocs.io

rules:
  - name: "Find PDF content"
    locations:
      - ~/Documents/Scanned Documents/Documents
    subfolders: true
    filters:
      - extension: pdf
      - filecontent
    actions:
      - echo: "{filecontent}"
```
