### ISSUE TITLE
OCR read and ai to rename and categorize 

### ISSUE THREAD

**Issue by neonnightsnz** [tfeldmann/organize#329]
OCR and chatgpt could be used to read pdf docs and give them a more appropriate name and category 

files would be scanned and pop up approving the new name and category manna adjustment and corrected. Data from this processing would be used to create a sorting models

https://nanonets.com/ http://www.dropitproject.com/

**Comment by tfeldmann** [comment]
Hi, thanks for the ticket. This is possible right now with a `python` filter and the confirm module.
Something like this:

```yaml
rules:
  - locations: .
    filters:
      - python: |
          # AI help here:
          import random
          num = random.randint(1, 1000)

          return {
            "ai_name": f"new-name-{num}.txt"
          }
    actions:
      - confirm: "Should this file be renamed to {python.ai_name}?"
      - echo: "Renaming..."
```
