### ISSUE TITLE
File Size Filter

### ISSUE THREAD

**Issue by mope1** [tfeldmann/organize#33]
This is a feature request for filtering files by size like so:

```
rules:
  - folders: '~/Downloads'
    filters:
      - Filesize:
          bigger: 500m
    actions:
      - Trash
```

I built this already but need to remake the PR for reasons so I might as well get an issue number here and name my branch correctly.
