### ISSUE TITLE
Destination with '@' character in name = copied to wrong path

### ISSUE THREAD

**Issue by notDavid** [tfeldmann/organize#332]
**Describe the bug**
Hi there,

i'm trying to copy files to a folder which is a "cloud folder" mounted from the "Proton Drive" app. The folder name contains the '@' character, and it seems Organize can't handle this;

Instead of to the destination folder, the files get copied to the current working dir, in a folder with the path of everything that comes "after" the `@` sign.

**Environment (please complete the following information):**
- OS: macOS 14.2.1
- Output of `organize --version`: organize, version 2.4.3

**Your config file**

```yaml
rules:
  - name: docs
    targets: "files"
    locations:
      - path: "/Users/david/Documents"
    filters:
      - not macos_tags: 'organize_exclude (*)'
      - lastmodified:
          days: 30
          mode: newer
    actions:
      - copy:
          dest: '/Users/david/Library/CloudStorage/ProtonDrive-xxxx@xxxx.xx/Documents.copy/'
```

Here, the files get copied to:  `./xxxx.xx/Documents.copy/`
