### ISSUE TITLE
[v3] unable to access created.strftime in a destination path

### ISSUE THREAD

**Issue by carpii** [tfeldmann/organize#340]
I upgraded to v3, and having a problem with one of my existing rules

It moves a `data.ofx` to another dir, and also renames it to have a "YYYYMMDD" prefix, based on the creation date of the source file

```yaml
rules:
  - name: "Copy OFX to syncbox"
    locations: ~/dev/barclays
    subfolders: false
    filters:
      - extension: ofx
      - name:
          match: data
          case_sensitive: false
      - created
    actions:
      - echo: "Copying OFX to syncbox/accounts/{created.strftime('%Y%m%d - Barclays.ofx')}"
      - move: 
         dest: "~/syncbox/accounts/{created.strftime('%Y%m%d - Barclays.ofx')}"
         on_conflict: overwrite
    tags:
      - barclays
```

Whilst I can access `created.strftime` in the `echo` command, when I then use it the `dest` of a `move` command it fails.

```
[carpii@beep:~]$ org --version
organize v3.0.0

[carpii@beep:~]$ org run --tag barclays
Config: "/home/carpii/.config/organize/config.yaml"

⚙ Rule #2: Copy OFX to syncbox ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
/home/carpii/dev/barclays
  ./data.ofx
    - (echo) Copying OFX to syncbox/accounts/20240111 - Barclays.ofx
    - (move) ERROR! Missing value for template: 'builtin_function_or_method object' has no attribute 'strftime'. Maybe you forgot a filter?

success 0 / fail 1
```

**Comment by tfeldmann** [comment]
Hi thanks for reporting! I've written multiple tests and cannot reproduce this. Which OS and python version are you on?

**Comment by carpii** [comment]
Hi,

I'm using Arch `6.6.9-arch1-1` and python `3.11.6`

organize is out of date on Arch repos, and then installed into a virtual env using `pipx install "organize-tool[texttract]"`

**Comment by carpii** [comment]
I created a simpler example which does work, although it's not that clear whats different

`> touch ~/foo.bar`

````yaml
  - name: "Rename FOO"
    locations: ~/
    subfolders: false
    filters:
      - extension: bar
      - name:
          match: foo
          case_sensitive: false
      - created
    actions:
      - echo: "Rename foo.bar to {created.strftime('%Y%m%d - foo.bar')}"
      - move: 
         dest: "~/{created.strftime('%Y%m%d - foo.bar')}"
         on_conflict: overwrite
    tags:
      - foobar
````

````
Config: "/home/carpii/.config/organize/config.yaml"

⚙ Rule #2: Rename FOO ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
/home/carpii
  ./foo.bar
    - (echo) Rename foo.bar to 20240112 - foo.bar
    - (move) Move to /home/carpii/20240112 - foo.bar

success 1 / fail 0
````
