### ISSUE TITLE
documented attributes for `rename` action specify `name` instead of `new_name`

### ISSUE THREAD

**Issue by kelbyers** [tfeldmann/organize#341]
**Describe the bug**
The `rename` action documentation specifies attributes `name`, `on_conflict`, and `rename_template`. 

https://github.com/tfeldmann/organize/blob/e6bbeb3cd224f81e131b0852abd1c70c0dabd7a7/organize/actions/rename.py#L21-L32

The actual code uses `new_name` instead of `name`:
https://github.com/tfeldmann/organize/blob/e6bbeb3cd224f81e131b0852abd1c70c0dabd7a7/organize/actions/rename.py#L37

**Screenshots**
![image](https://github.com/tfeldmann/organize/assets/1743077/7f1181ae-5898-4f5f-9525-57ae6a8d3b1a)

**Environment (please complete the following information):**

- OS: 
  Windows

- Output of `organize --version`:
  `organize v3.0.1`

**Your config file**

```yaml
  - name: pwSafe rectify backup names
    locations:
      - ~/Dropbox/pwsafe
    filters:
      - extension:
        - ibak
        - bak
      - lastmodified
      - name
      - python: |
          if name == "pwsafe": return False
          ts_name = relative_path.stem.split('_')[0] + "_" + lastmodified.strftime('%Y%m%d_%H%M%S') + ".ibak"
          if str(relative_path) != ts_name:
            return { "ts_name": ts_name }
    actions:
      - echo: "{relative_path} : {python.ts_name}"
      - rename:
          name: "{python.ts_name}"
          on_conflict: trash
```
