### ISSUE TITLE
Avoiding 0-byte files being created when encountering "No space left on device"

### ISSUE THREAD

**Issue by tordenflesk** [tfeldmann/organize#342]
Yes. Anyway of avoiding 0-byte files being created when encountering:

ERROR! [Errno 28] No space left on device

_Originally posted by @tordenflesk in https://github.com/tfeldmann/organize/issues/191#issuecomment-1892720462_

**Comment by tfeldmann** [comment]
Which actions result in empty files? Moving / copying?

**Comment by tordenflesk** [comment]
Moving

```
rules:
  - locations: \\Srv-omv01\data01\tdarr\output
    name: Tdarr
    subfolders: true
    filters:
      - extension: mkv
      - lastmodified:
          minutes : 10
    actions:
      - move:
          dest: G:\
          on_conflict: rename_new
          rename_template: "{name}-{counter}{extension}"
```
