### ISSUE TITLE
Move action deletes file info

### ISSUE THREAD

**Issue by PuppyNami** [tfeldmann/organize#343]
**Describe the bug**
When using the action move it erases info like creation date and modified date and sets it to the time the tool was executed

**Environment (please complete the following information):**

- OS: Microsoft Windows 11 Pro Version	10.0.22631 Build 22631
- Python version: 3.12
- Output of `organize --version`: organize, version 2.4.3

**Your config file**

```yaml
# organize configuration file
# https://organize.readthedocs.io

rules:
  - name: "Testing"
    locations:
      - D:/Windows/Downloads/Chrome
    filters:
      - mimetype: image
      - extension
      - created
      - name:
          contains: "test"
          case_sensitive: false
    actions:
      - echo: '"{name}.{extension}" "{created}"'
      - move:
          dest: "D:/Windows/Downloads/Chrome/test/"
      - echo: '"{path}"'
```
