### ISSUE TITLE
Can't use actions, even if copied rules from documentation

### ISSUE THREAD

**Issue by PuppyNami** [tfeldmann/organize#352]
**Describe the bug**
When using actions like move, trash and delete, not tested the others, I get a validation error from my config that looks like this:
```
Error: Config problem
1 validation error in "C:\Users\UserName\AppData\Local\organize\organize\config.yaml"

rules.0.actions.0
  Input should be an instance of Action [input_value="Delete()", input_type=Delete]
```

**Environment (please complete the following information):**

OS: Microsoft Windows 11 Pro Version 10.0.22631 Build 22631
Python version: 3.12.2
Output of organize --version: organize, version 3.1.0

**Your config file**

```yaml
all_my_messy__download_folders: &download_folders
  - D:/Windows/Downloads/Chrome
  - D:/Windows/Downloads/Chrome/Other

rules:
  - name: "Delete Duplicate"
    locations: *download_folders
    filters:
      - duplicate:
          detect_original_by: "created"
    actions:
      - delete
```
