### ISSUE TITLE
Encoding Windows

### ISSUE THREAD

**Issue by random623** [tfeldmann/organize#36]
Hey,

I'm trying to use organize with Windows 10/Python 3.7.3 and have a problem with the encoding (ü/ö/ä).

Example:
```
rules:
  # move Übungen to 'Übungen' folder
  - folders: 'D:\test'
    subfolders: true
    filters:
      - Extension:
        - txt
      - Filename:
          contains : übung
          case_sensitive: false
    actions:
      - Move: 'D:\test\übungen\'
```

The tools is not finding the "übung.txt".

With the following config it finds the file but the move folder is wrong.

```
rules:
  # move Übungen to 'Übungen' folder
  - folders: 'D:\test'
    subfolders: true
    filters:
      - Extension:
        - txt
      - Filename:
          contains : bung
          case_sensitive: false
    actions:
      - Move: 'D:\test\übungen\'
```
organize run gives the following output:
```
PS C:\Users\jn> organize run
Folder D:\test\:
  File übungen.txt:
    - [Move] Move to "D:\test\Ã¼bungen\übungen.txt"
```

The result is the file in a new folder named "Ã¼bungen"

Maybe some ideas where to look? The file "übung.txt" is displayed correct. Thanks

Cheers,
Jan
