### ISSUE TITLE
Moving a file to a NAS server triggers an error

### ISSUE THREAD

**Issue by robolth** [tfeldmann/organize#373]
Moving a file to a NAS Server triggers an error. The file is copied, but the original is not removed.
This did not happen with v2.
I believe this is the same issue as in this SO thread: [https://stackoverflow.com/questions/18621577/errno-22-with-python-shutil-and-move-function](url)

Output of `organize run`:
```Python
⚙ Rule #0: Move file to NAS volume
 ──────────
/Users/user/Downloads/file.txt
    - (move) Move to /Volumes/NAS-volume/file.txt
    - (move) ERROR! [('/Users/user/Downloads/file.txt', '/Volumes/NAS-volume/file.txt', "[Errno 22] 
Invalid argument: '/Volumes/NAS-volume/file.txt'")]
```
Please note that the file *has* been copied to the NAS volume despite the error. The original, however, has not been removed.

- OS: macOS Sonoma 14.4
- Output of `organize --version`: organize v3.2.2

**Your config file**

```yaml
rules:
  - name: "Move file to NAS volume"
    locations: "/Users/user/Downloads/"
    subfolders: false
    filters:
      - extension: txt
    actions:
      - move:
          dest: "/Volumes/NAS-volume/"
          on_conflict: "skip"
```
