### ISSUE TITLE
[Trash] ERROR! File not found

### ISSUE THREAD

**Issue by gregoriopellegrino** [tfeldmann/organize#38]
Hi,
thanks for this software. I run it at every login, for cleaning the Downloads folder, but when a file is moved to the trash i get this error:

`[Trash] ERROR! File not found`

**Comment by tfeldmann** [comment]
Hi! Can you post your config file here? I can‘t tell what’s wrong from this error message.

**Comment by gregoriopellegrino** [comment]
Here you have:
```
rules:
    # move incomplete downloads older > 7 days into the trash
    - folders:
        - ~/Downloads
      filters:
        - LastModified:
            days: 7
      actions:
        - Trash
```
