### ISSUE TITLE
Copy folder structure from parent folder, monitored folder, or root folder

### ISSUE THREAD

**Issue by nothing2obvi** [tfeldmann/organize#387]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to copy or move certain file extensions from a folder to another folder but keep the same folder/subfolder structure. I'm not sure how to currently do this in Organize.

**Describe the solution you'd like**
Allow copying or moving certain files while keeping the same folder/subfolder structure, similar to Hazel.

![Screen Shot 2024-05-05 at 1 57 35 PM](https://github.com/tfeldmann/organize/assets/85228035/a118c1db-6300-4bae-820f-1530168fcc56)

**Describe alternatives you've considered**
My alternative is Hazel. I've already made the switch to Organize for most tasks, but this feature is something I'm only able to do in Hazel at the moment.

**Comment by tfeldmann** [comment]
Have a look at the `{relative_path}` variable:

```yaml
rules:
  - locations: "/test"
    subfolders: true
    filters:
    - name:
        startswith: file
    actions:
    - copy: "/dest/{relative_path}
```

Does this work for you?
