### ISSUE TITLE
Shell command fails

### ISSUE THREAD

**Issue by florianklumb** [tfeldmann/organize#391]
**Describe the bug**
Steps to reproduce (I think):

Add the following rule:
```yaml
- name: POC 
    locations: ~/Downloads/
    filters:
        - extension: pdf
    actions:
        - shell:
            cmd: "python -c 'import datetime; print(datetime.date.today())'"
            run_in_simulation: true
            #ignore_errors : true
        - echo: '{shell.output}'
```
When running without `ignore_errors : true`, I get this error:

```bash
⚙ Rule #1: POC ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
C:\Users\.../Downloads
  ./xyz.pdf
    - (shell) $ python -c 'import datetime; print(datetime.date.today())'
    - (shell) ERROR! Command 'python -c 'import datetime; print(datetime.date.today())'' returned non-zero exit status 1.
```

When running with  `ignore_errors : true`, I get:

```bash
⚙ Rule #1: POC ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
C:\Users\.../Downloads
  ./xyz.pdf
    - (shell) $ python -c 'import datetime; print(datetime.date.today())'
    - (shell) ERROR! cannot access local variable 'call' where it is not associated with a value
```

**Environment (please complete the following information):**

- OS: Windows 10
- Output of `organize --version`: organize v3.2.3
