### ISSUE TITLE
EXIF Filter does not work with PDF's

### ISSUE THREAD

**Issue by svHatch** [tfeldmann/organize#419]
**Describe the bug**
`exiftool` from the shell works on PDF files to reveal metadata. The `exif` tag in organize silently skips PDF files without explanation.

Either this is on purpose, in which case there should be info either in the docs or in the output of the rule that `exif` doesn't work on PDF files, unlike when used from the shell.

Or, this is a feature request to include PDF files in the `exif` filter.

**Environment (please complete the following information):**

- OS: 
------------------------- 
OS: Linux Mint 22 x86_64 
Host: 2342CTO ThinkPad T430 
Kernel: 6.8.0-45-generic 
Shell: bash 5.2.21 
DE: Xfce 4.18 
WM: Xfwm4 
CPU: Intel i7-3520M (4) @ 3.600GHz 
GPU: Intel 3rd Gen Core processor Graphics Controller 
GPU: NVIDIA NVS 5400M 
Memory: 3208MiB / 6763MiB 

- Output of `organize --version`:
`organize v3.2.5`

**Your config file**

```yaml
rules:
  - name: "Check exif"
    locations: "."
    filters:
      - extension: pdf
      - exif
    actions:
      - echo: "This does not work"

  - name: "No Exif"
    locations: "."
    filters:
      - extension: pdf
      - name
    actions:
      - echo: "This works"

  - name: "Try with shell"
    locations: "."
    filters:
      - extension: pdf
    actions:
      - shell: 'exiftool {path} | grep "Date/Time"'
      - echo: "{shell.output}"
```
