### ISSUE TITLE
Surrogate (special characters) handling in Python

### ISSUE THREAD

**Issue by 314Sami** [tfeldmann/organize#429]
**Describe the bug**
Having files with special characters from Windows drives seems to cause problem. Not all special characters, though. It took many hours to figure what is the problem, as the filename(s) causing the error were not shown, only the ones before it and the error messages were not informative. 

Steps to reproduce:
1) Create/rename a file on Windows, the name containing special character like in Apocalypticas song Cortége. Scandic letters äöå work also sometimes, my guess is that filenames encoded in ISO-8859-1 will cause the error and modern "utf-8" wont. The main problem is that Windows handles surrogates differently. (Or if you don't want to make a file with problematic name for Python, there are online examples how to assign variable values so that they raise the error, for example https://stackoverflow.com/questions/27366479/python-3-os-walk-file-paths-unicodeencodeerror-utf-8-codec-cant-encode-s ).
2) Move the file to Linux filesystem.
3) Run 'organize run' with filters that match the file.
4) Receive error: ERROR! 'utf-8' codec can't encode character '\udcf6' in position 105: surrogates not allowed
Also others than dcf6 have been seen.

The program stops at the error and after deleting or renaming the file it needs to be started again and it takes a lot of time to get to the same spot.

**Temporary fix**
run the command with the following environmental variable set, the command will still produce errors but it will not crash. I will not quarantee that for example moving files would work with this "fix" so until there is a proper fix, I suggest to only print the files.

PYTHONIOENCODING=utf-8:surrogateescape organize run

**Screenshots**

**Environment (please complete the following information):**

- OS: Manjaro Linux
- Output of `organize --version`: organize v3.3.0

**Your config file**

```yaml
rules:
  - locations: /mnt/mydata
    subfolders: true
    filters:
      - extension:
        - mp3
        - flac
        - wav
        - ogg
      - size
    actions:
      - write:
          outfile: "music.txt"
          text: "{size.traditional} -- {path}"
          mode: "append"
```
