### ISSUE TITLE
Rename files with date

### ISSUE THREAD

**Issue by megusta-01** [tfeldmann/organize#43]
hey, is there a possibility to rename files like this, i've a file e.g.:
File_abc_datYYYYMMDD_xyz.pdf -> to -> File_DDMMYYYY.pdf

maybe with regex but i don't know how to use it

**Comment by tfeldmann** [comment]
Yes sure this is possible. Try something like this:
```
rules:
  - folders: ~/Desktop/YourFolder
    filters:
      - regex: 'File_.*?(?P<y>\d{4})(?P<m>\d{2})(?P<d>\d{2}).*?.pdf'
    actions:
      - rename: "File_{regex.d}{regex.m}{regex.y}.pdf"
```

The regex looks intimidating, but it is just named groups of digits for day, month and year: https://regex101.com/r/DOBJRh/1/
