### ISSUE TITLE
Final block in Actions

### ISSUE THREAD

**Issue by Programazing** [tfeldmann/organize#439]
**Is your feature request related to a problem? Please describe.**

Since action runs once per file, it's challenging to have something trigger at the end of the run.  I'm frustrated because, although I can echo something into a log file, it happens once per file.

**Describe the solution you'd like**

I want to see something like 

```
rules:
  - name: "Move Documents to Documents directory"
    locations:
      - ~/Downloads
    filters:
      - name
      - extension:
          - txt
          - pdf
    actions:
      - move: ~/Documents
      - shell: 'echo "Moved {name} to Documents" >> ~/move_log.txt'
      - final:
           - shell: 'echo "All files moved at  {time} >> ~/move_log.txt"
```

**Describe alternatives you've considered**

I haven't, as I didn't see anything in the documentation that suggests this can be changed.

**Additional context**
