### ISSUE TITLE
file content of PDFs is not detected

### ISSUE THREAD

**Issue by wbeck77** [tfeldmann/organize#450]
**Describe the bug**
I´m running a sample rule from the documentation. (see below)
Whenever I add the filter for the file content I get "Nothing to do" as result
if I remove the filter end change echo to "hello" I get one "hello" per file
I testes with apps. 100 files. some are scanned with OCR, others are originally with text (like a downloaded documentation for example)

**Environment (please complete the following information):**
I´m running on MacOS 15.4.1 with organize version 3.3.0

**Your config file**

rules:
  - name: "Show the content of all your PDF files"
    locations: ~/Documents
    filters:            
      - extension: pdf
      - filecontent   
    actions:                
      - echo: "{filecontent}"

**Comment by MyVizDrake** [comment]
I have the same problem, though on Windows with organize installed via scoop.sh. 

I have poppler installed as well (via scoop.sh) and pdtotext runs from any command shell (i.e. it is in the PATH). I can run pdftotext and get appropriate txt files in the directory so pdftotext is working. 

This results in nothing as well ...
```
- name: "Show the content of all your PDF files"
    locations: "D:\\Some Folder\\User\\Family\\Some Directory\\Test"
    filters:
      - extension: pdf
      - filecontent
    actions:
      - echo: "{filecontent}"
```

```organize sim``` results in "Nothing to do"

only thing I can think of is needing to ```pip install --use-pep517 python-poppler``` but I would think that since pdftotext is working from the same shell organize is run from it should not be necessary.

I did install pdfminer as well via ```pip install pdfminer``` but there is no change in behavior

Perhaps OP and I are doing something collectively wrong.  Appreciate the help!
