### ISSUE TITLE
How to act on a file only when it's finished downloading?

### ISSUE THREAD

**Issue by danbohea** [tfeldmann/organize#58]
I have a rule in my ~/Downloads directory that seems to fire as soon as the file download starts and then repeatedly while it continues to download. This doesn't end well as I'm sure you can guess. How do I ensure that actions are only performed once the file has finished downloading?

I'm using Kubuntu 19 and using Firefox to download the file, in case any of that matters. Here's the rule in question:

```yaml
rules:

  # Downloads: Extract "backstop_data" tar files, open the HTML report and send a notification.
  - folders:
      - ~/Downloads
    filters:
      - filename:
          startswith: backstop_data
    actions:
      - shell: 'tar xvf {path} -C {basedir}'
      - shell: "xdg-open /home/dan/Downloads/backstop_data/html_report/index.html"
      - shell: "notify-send 'organize rule ran' '{path}' -u low -i folder"
```

I'm using `inotify-hookable` to watch the directory for modifications:

```sh
# ~/.bash_profile
inotify-hookable -w ~/Downloads -c "organize run" --no-r &
```

**Comment by tfeldmann** [comment]
Sorry for the late reply! I just tested this with Firefox on macOS. It seems like firefox creates a `.part` file while downloading.
![Bildschirmfoto 2020-03-04 um 15 23 47](https://user-images.githubusercontent.com/385566/75888894-5a9c8300-5e2c-11ea-8806-380915143f33.png)

You can use this to exclude incomplete downloads:
```yaml
rules:
  - folders: "~/Downloads/"
    filters:
      - filename:
          startswith: backstop_data
      - extension: gz # to exlude .part extension
      - python: |
          partfile = path.with_suffix(path.suffix + ".part")
          # return True if we have a match
          return not partfile.exists()
    actions:
      - echo: "Found complete download: {path}"
```
