### ISSUE TITLE
Use Exif datetime tag for file renaming 

### ISSUE THREAD

**Issue by ChristianL82** [tfeldmann/organize#59]
Hi,

I tryed to add the date of creation to the filename of my images. With the following code I get the date of creation in a format like this: "2019:01:19 15:23:33". 

```
rules:
  - folders: ~/Desktop/Bilder
    enabled: false
    subfolders: false
    filters:
      - exif:
          image.datetime
    actions:
      - echo: "{exif.image.datetime}"
```

How could I modify this tag, so I could use this for renaming and get image names like this: "190119_15-23-33_IMG"?  And how do I invert the Exif filter to get all images without Exif informations.

Thanks a lot!
Christian
