### ISSUE TITLE
Copy multiple files to separate folders

### ISSUE THREAD

**Issue by neodata83** [tfeldmann/organize#64]
Hello

I am trying to make your Program work but it gives me errors. I use The docker container from dskaggs to let it run on my server. There is an Folder when files with specific filename appears depending on the filename it moves it to its on folder. My Configfile looks like that but i don't know whats wrong.

Ruben

```
rules:
  - folders: /source
    subfolders: true
    filters:
      - filename:
            contains: Example1
            case_sensitive: false
    actions:
      - echo: 'File Found'
      - copy:
          dest: '/destination/Example1/'
          overwrite: true


- folders: /source
    subfolders: true
    filters:
      - filename:
            contains: Example2
            case_sensitive: false
    actions:
      - echo: 'File Found'
      - copy:
          dest: '/destination/Example2'
          overwrite: true
```

**Comment by tfeldmann** [comment]
The indentation of your config file is a bit off. Can you try this one?

```yaml
rules:
  - folders: /source
    subfolders: true
    filters:
      - filename:
          contains: Example1
          case_sensitive: false
    actions:
      - echo: 'File Found'
      - copy:
          dest: '/destination/Example1/'
          overwrite: true

  - folders: /source
    subfolders: true
    filters:
      - filename:
          contains: Example2
          case_sensitive: false
    actions:
      - echo: 'File Found'
      - copy:
          dest: '/destination/Example2'
          overwrite: true

```
