### ISSUE TITLE
ERROR! 'lastmodified' & ERROR! 'created'

### ISSUE THREAD

**Issue by agentesmith87** [tfeldmann/organize#66]
Hi, I'm testing a config to move some files in subdirectories having name of the year, month, date, ecc ecc of creation or last modification.
The config seems to be ok but everytime I run sim I get these errors both trying with lastmodified and created properties.

Here my simple config

`rules:
  - folders: '/media/scheduled'
    subfolders: true
    filters:
      - extension: jpg
      
    actions:
     - move: '~/media/foto/{lastmodified.year}/{lastmodified.month}/{lastmodified.day}/{lastmodified.year}-{lastmodified.month}-{lastmodified.day} {lastmodified.hour}:{lastmodified.minute}/'`

It doesn't work either if I use a simpler version with only one subfolder attribute.

`File Schedule_20180802-052137.jpg:
    - [Move] ERROR! 'created'
`
`  File Schedule_20170128-124732.jpg:
    - [Move] ERROR! 'lastmodified'
`

EDIT: Still not working with same error if I only echo lastmodified.year or created.year

**Comment by tfeldmann** [comment]
Hi! To be able to access the `lastmodified` and `created` variables you have to add these to the filters. A working example:

```yaml
rules:
  - folders: '/media/scheduled'
    subfolders: true
    filters:
      - extension: jpg
      - lastmodified
    actions:
      - move: '~/media/foto/{lastmodified.year}/{lastmodified.month}/{lastmodified.day}/{lastmodified.year}-{lastmodified.month:02}-{lastmodified.day:02} {lastmodified.hour:02}:{lastmodified.minute:02}/'
```

(I added the `:02` formatters to ensure a leading zero on minutes, hours, days and month)

And have a look at the [`exif-filter`](https://organize.readthedocs.io/en/latest/page/filters.html#filters.Exif): with this you can extract the date and time directly from your picture metadata. This might fit your use-case even more?
