### ISSUE TITLE
Flatten filter and action lists for code reusability

### ISSUE THREAD

**Issue by rawdamedia** [tfeldmann/organize#67]
YAML has a merge operator for combining dictionaries, but it does not have a native way of merging ordered lists.

I see that you already have ["Flatten filter lists?"](https://github.com/tfeldmann/organize/projects/4#card-25088431) in your [Roadmap](https://github.com/tfeldmann/organize/projects/4), and I would suggest that you do the same for actions to allow for code reusability in the config file.

Often filters and actions have many parts in common between rules.  Instead of repeating the same filters and actions everywhere, flattening filters and actions lists can allow one to do something like this:
```yaml
folder_aliases:
  Downloads: &downloads ~/Downloads/
  Payables_due: &payables_due ~/PayablesDue/
  Payables_paid: &payables_paid ~/Accounting/Expenses/
  Receivables_due: &receivables_due ~/Receivables/
  Receivables_paid: &receivables_paid ~/Accounting/Income/

regex_patterns:
  long_date: &date_long '(?P<date>\d{1,2}\s(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\w{,8}\s20\d{2}))'
  any_date: &date_any "(?P<date>\
    (\\d{1,2}.{,3}(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\\w{,8}.{,3}20\\d{2})|\
    ((([0-2]?\\d)|(3[01])).((0\\d)|(1[0-2])).((20)?\\d{2}))\
    )"

python_code:
  timestamp_and_quarter: &timestamp |
    from dateutil.parser import parse
    dat = parse(filecontent.date)
    ts = dat.strftime('%Y%m%d')
    q = dat.strftime('%Y') + 'Q' + str((2 + int(dat.month)) // 3)
    return {'timestamp': ts, 'quarter': q}

defaults:
  filters: &default_filters
    - extension: pdf
    - filecontent: *date_any
    - python: *timestamp
  actions: &default_actions
    - echo: 'Dated: {filecontent.date}'
    - echo: 'Stem of filename: {filecontent.stem}'
    - echo: 'Timestamp: {python.timestamp}'
    - echo: 'Quarter: {python.quarter}'
  post_actions: &default_sorting
    - rename: '{python.timestamp}-{filecontent.stem}.{extension.lower}'
    - move: '{path.parent}/{python.quarter}/'

Rule_in_development: &DEV
  enabled: false
  actions: *default_actions

Rule_stable: &PROD
  enabled: true

rules:
  - <<: *PROD
    folders: *downloads
    filters: 
      - *default_filters
      - filecontent: '' # regex to id as payable
      - filecontent: '(?P<stem>...)' # regex to extract supplier
    actions: 
      - *default_actions
      - move: *payables_due
      - *default_sorting

  - <<: *PROD
    folders: *downloads
    filters: 
      - *default_filters
      - filecontent: '' # regex to id as receivables due
      - filecontent: '(?P<stem>...)' # regex to extract customer
    actions: 
      - *default_actions
      - move: *receivables_due
      - *default_sorting

  - <<: *PROD
    folders: *downloads
    filters: 
      - *default_filters
      - filecontent: '' # regex to id as receivables paid
      - filecontent: '(?P<stem>...)' # regex to extract customer
      - filecontent: '(?P<paid>...)' # regex to extract date paid
    actions: 
      - *default_actions
      - move: *receivables_paid
      - *default_sorting
      - rename: '{filecontent.paid}_{filecontent.stem}.{extension}'
```
Having all the code at the top of the config file and reducing duplication makes it easier to debug.

Cheers!

PS: I have only just discovered your tool and am already finding it incredibly useful!
