### ISSUE TITLE
Multiple problems with the PY code ...

### ISSUE THREAD

**Issue by GitHubCommunityProjects** [tfeldmann/organize#7]
on Linux KDE Kubuntu 18.04

When I try to run a configuration with some simple example like the ones you provide on your web page, the program returns errors, among others, for example:

rules:
   - folders:'˜/Desktop'
     filters:
        - LastModified:
             - days: 10
     actions:
          - Echo: 'Was modified at least 10 days ago'

Return me...

ERROR! unsupported type for timedelta days component: dict

into last_modified.py file code appear (lines 82 and 83 on my file)...

self.timedelta = timedelta(
days=days, hours=hours, minutes=minutes, seconds=seconds)

with others examples others error too. Thanks.

**Comment by tfeldmann** [comment]
I guess there is something wrong with your configuration. Your folders, filters and actions should have the same level of indentation:

```yaml
rules:
  - folders: '~/Desktop'
    filters:
      - LastModified:
          days: 10
    actions:
      - Echo: 'Was modified at least 10 days ago'
```

This example should work fine. Otherwise could you please paste your config here again between backticks like this:

````yaml
```yaml
your config here
```
````
 This will make the whitespace is not lost.
Does is work now?
