### ISSUE TITLE
startswith doesn't work with accents

### ISSUE THREAD

**Issue by misterio2051** [tfeldmann/organize#74]
As the title says. I have the following rule:

```yaml
# Cálculo PDF
rules:
  - folders: ~/Google Drive/
    subfolders: false
    filters:
      - extension:
         - pdf
      - filename:
          startswith: Cálculo 
    actions:
      - move: "~/Google Drive/Escuela/12vo/Cálculo Integral/Periodo #6/PDF's/"
```
I've tried adding quotations to the startswith argument but it still doesn't work.
