### ISSUE TITLE
organize all documents by moving them into folder by kind and renaming them (prepend with date)

### ISSUE THREAD

**Issue by AtomicNess123** [tfeldmann/organize#76]
Hi, 

I'm trying to do this action, and wondered if any of you had it already so they could share it. 
The rule should go along these lines:
```yaml
rules:
  - folders: ~/Downloads
    filters:
      - extension:
          - pdf
          - jpg
    actions:
      - move:
          dest: '~/Downloads/{extension.upper}/'
          overwrite: true
```
What I am missing is to include ANY kind (not just PDF and JPG), without having to specify it (so the rule would detect a specific KIND and sort it automatically). I am not sure if this is possible. Also, I am not sure how to create the part that renames the documents.
Thanks a log in advance, wonderful tool!

**Comment by tfeldmann** [comment]
To have the `extension` variable available in actions without filtering for extensions simply omit the list of extensions to filter:

```yaml
rules:
  - folders: ~/Downloads
    filters:
      - extension
    actions:
      - move:
          dest: '~/Downloads/{extension.upper}/'
          overwrite: true
```

> Also, I am not sure how to create the part that renames the documents.

What do you mean by that? You can access all `pathlib.Path` properties via the `path` variable:
```yaml
      - move:
          dest: '~/Downloads/{extension.upper}/{path.stem}{path.suffix}'
```
Is that what you mean?

**Comment by Gahamelas** [comment]
Ok, I see! Thank you very much. I did not know of the "- extension" possibility under filters (which I assume includes all possible extensions). Regarding the renaming part, I am not sure if 

`  dest: '~/Downloads/{extension.upper}/{path.stem}{path.suffix}'`

does that. I want the documents to be renamed by prepending the date (2020-05-01 NAMEOFFILE), if it makes sense, when moved to their extension folders.

Thanks again, 
GM

**Comment by tfeldmann** [comment]
Yes, sure thats possible. You can compose the filename however you like.

The only problem is that organize gives you only the `lastmodified` and `created`-dates. To get the current date we have to use a little workaround:

```yaml
rules:
  - folders:
      - ~/Downloads
      # exclude dotfiles
      - ! ~/Downloads/.*
    filters:
      - extension
      - python: |
          from datetime import date
          return {"today": date.today().strftime("%Y-%m-%d")}
    actions:
      - move:
          dest: '~/Downloads/{extension.upper}/{python.today} {path.stem}{path.suffix}'
          overwrite: true

```

In the next version of organize I'll add a `today` variable so that the python filter is no longer needed!
