### ISSUE TITLE
"Created before today"

### ISSUE THREAD

**Issue by Gahamelas** [tfeldmann/organize#78]
I haven't found a way to filter all files created _before today_.
I found the following:

```
      - created: 
          days: 1 
```

However, this isn't the same as _before today_, as I noticed that it will be applied to files created exactly 24 hours ago that the current time.

I wonder if there is a way to achieve this using the organize resources.
Thanks!

**Comment by Gahamelas** [comment]
Anybody any help? :)

**Comment by tfeldmann** [comment]
You can do this with the help of a python filter:

```yaml
rules:
  - folders: ~/Desktop
    filters:
      - created
      - python: |
          from datetime import datetime
          return created.date() < datetime.now().date()
    actions:
      - echo: "Created before today: {path}"
```

I think having this built in the `created`-filter would benefit a lot of people so I'm going to add this to a future version, I'm just not sure about the syntax yet. So thank you for the issue!
