### ISSUE TITLE
Maintaining subfolder tree on move action? 

### ISSUE THREAD

**Issue by rtgoodwin** [tfeldmann/organize#8]
Can't seem to figure this one out. 

Given a folder structure:
`~/Downloads/SomeFontPackage/SomeFolder/font.ttf`

I can't figure out how to do a Move with a `ttf` extension that will let me move to say:
`~/Downloads/FONTS/SomeFontPackage/SomeFolder/font.ttf`
(the goal being maintaining the folder structure)

I tried messing with the paths, including trying the `{path.relative_to('~/Downloads)}`, following the PurePath documentation, but I get: 
```
File lily_of_the_valley/Lily of the Valley.ttf:
    - [Move] ERROR! Missing template variable 'PosixPath' object has no attribute 'relative_to('/Users/MYUSER/Downloads')' for "~/Downloads/FONTS/{path.relative_to('/Users/MYUSER/Downloads')}/"
```

I know you can chain paths and parents, but it seems like a guessing game of "how many parents might an item have."

FWIW my Python(s) are installed via brew on macOS High Sierra: 

```
12:00 $ which python
/usr/bin/python
✔ ~/Downloads
12:04 $ which python3
/Library/Frameworks/Python.framework/Versions/3.6/bin/python3
```

I'm sure I'm missing something simple. Thanks for your hard work on this! I want to get it going and then just cron it (or equivalent). 😄

**Comment by rtgoodwin** [comment]
I even tried to get fancy with some regex love, but organize isn't finding anything when simulated:

```
    filters:
      - Regex: '^(?P<the_path>.*/).*\.ttf$'
    actions:
      - Move: ~/Downloads/FONTS/{regex.the_path}
      - Trash
```
Again, sure it's something easy I'm just missing 😄

**Comment by tfeldmann** [comment]
You are not missing something... organize focuses on filenames at the moment and is seriously lacking support for folder structures.
As a workaround you can do something like this:

```yaml
rules:
  - folders:
      - ~/Downloads
    subfolders: true
    filters:
      - Extension: ttf
    actions:
      - Python: |
          import shutil
          relpath = path.relative_to(basedir)
          if relpath.parts[0] != 'FONTS':
            newpath = basedir / 'FONTS' / relpath
            newpath.parent.mkdir(parents=True, exist_ok=True)
            print(f'Moving file to {newpath}')
            shutil.move(path, newpath)
          else:
             print('Ignored')
```

The next step would be to delete the empty directories left behind. I added this to the todo list 👍 

To be honest I haven't got a good idea how to deal with folder structures. Maybe making the path relative to the basedir available to the actions by default is a good first step. Anyway - thank you for opening the issue. There are many things to improve here.

**Comment by tfeldmann** [comment]
This bugged me a lot so I just uploaded a new version of organize.
Please update organize with `pip3 install -U organize-tool` and try it out:

```yaml
rules:
  - folders:
      - '~/Downloads/*[!FONTS]/**/*.ttf'
    actions:
      - Move: '{basedir}/FONTS/{relative_path}'
```
