### ISSUE TITLE
How to trim a string

### ISSUE THREAD

**Issue by gvg-h-de** [tfeldmann/organize#80]
First of all, thank you very much for "organize". I have running this in a container on a Synology and in combination with synOCR it helps a lot in getting all the scanned pdfs to the my document structure.

Actually i try to parse all my pdfs and check them with the regex filter. Due to the fact, that the OCR sometimes produces some lines in between i have to look for them with \s*

```
  filters:
      - extension: pdf
      - filecontent: (?P<wwkcode>\d{2}\s*\d{3}\s*\d{3})

```

Then i want to use the result from regex within the filename, so i use:

```
    actions:
      - echo: "Found Insurance PDF"
      - rename: "{created.year}-{created.month:02}-{created.day:02}_WWK_{filecontent.wwkcode}.pdf"

```
Works like a charme, but when the result is inserted into the filename, also the white lines are there (of course). I tried to trim the string using python, but i failed. Is there an easy way, to get rid of the the unwanted spaces?

I have tried it with:

```
      - python: |
        resulttext = filecontent.wwkcode
        return {"texting": resulttext.replace(" ", "")}

   actions:
      - echo: "Found WWK"
      - rename: "{created.year}-{created.month:02}-{created.day:02}_WWK_{filecontent.wwkcode}_{python.texting}.pdf"
```

But then it failed and the log gives me the following errors:

ERROR: while scanning a simple key
  in "<unicode string>", line 12, column 9:
            resulttext = filecontent.wwkcode
            ^
could not find expected ':'
  in "<unicode string>", line 13, column 9:
            return {"texting": resulttext.re ... 
            ^
Try 'organize config --debug' for easier debugging.
Full traceback at: /root/.cache/organize/log/organize.log

I really appreciate your help. Thanks in advance.

**Comment by tfeldmann** [comment]
It looks like a small formatting to me - can you try indenting your python code like this:

```yaml
      - python: |
          resulttext = filecontent.wwkcode
          return {"texting": resulttext.replace(" ", "")}
```

Thank you a lot for mentioning synOCR - I did not know about this and it's very helpful!

**Comment by gvg-h-de** [comment]
Hello,

thank you very much. But i think i have a structural error in my 
settings.
I have copied your text and now it is:

rules:
   # first test, move txt files away
   - folders: /source/
     subfolders: true
     filters:
       - extension: pdf
       - filecontent: (?P<wwkcode>\d{2}\s*\d{3}\s*\d{3})
       - created:
             days: 10
             mode: newer
       - python: |
       resulttext = filecontent.wwkcode
       return {"texting": resulttext.replace(" ", "")}
     actions:
       - echo: "Found WWK"
       - rename: 
"{created.year}-{created.month:02}-{created.day:02}_WWK_{filecontent.wwkcode}.pdf"
       - move: /destination/wwk/


But I still get the error:

ERROR: while scanning a simple key
   in "<unicode string>", line 12, column 7:
           resulttext = filecontent.wwkcode
           ^
could not find expected ':'
   in "<unicode string>", line 13, column 7:
           return {"texting": resulttext.re ...
           ^
Try 'organize config --debug' for easier debugging.
Full traceback at: /root/.cache/organize/log/organize.log

But maybe its a docker problem?

Kind regards,

Guido

------ Originalnachricht ------
Von: "Thomas Feldmann" <notifications@github.com>
An: "tfeldmann/organize" <organize@noreply.github.com>
Cc: "gvg-h-de" <info@vongoesseln.de>; "Manual" 
<manual@noreply.github.com>
Gesendet: 03.06.2020 13:22:56
Betreff: Re: [tfeldmann/organize] How to trim a string (#80)

**Comment by tfeldmann** [comment]
It still seems like a indentation error in the `python`-filter. Can you paste your config again and format it as code here?

Correctly indented it should look like this:
```yaml
rules:
  # first test, move txt files away
  - folders: /source/
    subfolders: true
    filters:
      - extension: pdf
      - filecontent: (?P<wwkcode>\d{2}\s*\d{3}\s*\d{3})
      - created:
          days: 10
          mode: newer
      - python: |
          resulttext = filecontent.wwkcode
          return {"texting": resulttext.replace(" ", "")}
    actions:
      - echo: "Found WWK"
      - rename: "{created.year}-{created.month:02}-{created.day:02}_WWK_{filecontent.wwkcode}.pdf"
      - move: /destination/wwk/
```

Can you please test this and report the results?
