### ISSUE TITLE
Dependencies between rules OR having different config files

### ISSUE THREAD

**Issue by iburunat** [tfeldmann/organize#81]
First of all, thanks for this very useful tool. A more elegant way to automate file management than Hazel, with impressive potential. 

Now I have been using it for some time and came up with two questions:

(1) Is it possible to create dependencies between rules? Let's say I want the output of a rule (e.g., move images to folder X) to be the input of another one (do some processing on them).  When running `organize`, the first rule (moving images) would happen but the second rule (do some processing on them) would do nothing since at the moment of execution the folder was empty (only solution is to organise run twice).

(2) Or else, is it possible with the current version to have different config files (`config1.yaml`, `config2.yaml`) and run them individually?

**Comment by tfeldmann** [comment]
(1) At the moment organize gathers files for all rules first and then sorts by folder to minimize folder switches in the output log, so rules should not depend on each other at the moment. This behavior might not be optimal and I'm thinking about changing it to go through the rules one by one.

Anyway, your use-case sounds like it could be handled by having multiple actions? So something like this: 

```yaml
rules:
- folders: ~/Pictures/Example
  filters:
    - extension: jpg
  actions:
    - move: ~/Pictures/To-Process
    - echo: Processing {path}
    - shell: "your-process-cmd {path}"
```

If you have multiple processing steps that should be done in multiple rules you can use yaml-aliases: https://organize.readthedocs.io/en/latest/page/config.html#aliases

```yaml
my_process_pipeline: &process
  - move: ~/Pictures/To-Process/
  - echo: Processing {path}
  - shell: "your-process-cmd \"{path}\""

rules:
  - folders: ~/Desktop
    filters:
      - extension: jpg
    actions:
      - *process

  - folders: ~/Pictures
    filters:
      - extension:
          - jpg
          - png
    actions:
      - *process

```

Example output:
```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ SIMULATION ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Folder /Users/tfeldmann/Desktop:
  File Panorama.jpg:
    - [Move] Move to "/Users/tfeldmann/Pictures/To-Process/Panorama.jpg"
    - [Echo] Processing /Users/tfeldmann/Pictures/To-Process/Panorama.jpg
    - [Shell] $ your-process-cmd "/Users/tfeldmann/Pictures/To-Process/Panorama.jpg"

Folder /Users/tfeldmann/Pictures:
  File DSCF2408.JPG:
    - [Move] Move to "/Users/tfeldmann/Pictures/To-Process/DSCF2408.JPG"
    - [Echo] Processing /Users/tfeldmann/Pictures/To-Process/DSCF2408.JPG
    - [Shell] $ your-process-cmd "/Users/tfeldmann/Pictures/To-Process/DSCF2408.JPG"
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ SIMULATION ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Note that the `echo` and `shell` actions work with the new file location after `move`!

(2) You can use the `--config-file=<path>` command line option (`organize sim --config-file=/path/to/file`) or set the config file path in the `$ORGANIZE_CONFIG` environment variable.

**Comment by iburunat** [comment]
(1) Thanks, @tfeldmann , for the in-depth response! Certainly very useful tips to implement in my config file :). You are right that I can handle my use-case by having multiple actions.

However, I notice that I get an ERROR message when I run this rule which renames and moves an image:

```yaml
# renames images in /Download and moves to /Pictures/album
 - folders: ~/Downloads
   enabled: true
   filters:
     - created
     - extension:
         - jpg
         - png
   actions:
     - move: # and rename
         dest: '~/Pictures/album/{created.year}-{created.month:02}-{created.day:02}/{created.year}-{created.month:02}-{created.day:02}.{extension.lower}'
         overwrite: false
         counter_separator: '_'
```

```
ERROR:
         Folder /Downloads:
           File image.jpg:
             - [Move] Move to "/Users/ibburuna/Pictures/album/2018-10-09/2018-10-09_2.jpg"
             - (Created) ERROR! [Errno 2] No such file or directory: '/Downloads/image.jpg'
```

Despite of the ERROR, the output of the rule works fine and it does what it should do.
I have tried to first rename and then move, but the move action will not find the file after renaming.
So it's just the ERROR message what intrigues me.

(2) Thanks for pointing that out. Specifying the path would mean I can have different config files.
