### ISSUE TITLE
How to stop on a job / make it optional

### ISSUE THREAD

**Issue by seebi** [tfeldmann/organize#89]
Hi @tfeldmann ,

this more or less a feature request / RFC ...

Motivation: Some of my rules are
- optional in my work routine or
- I cannot decide automatically if they apply or
- I just do not trust them 100%

I would like to have them optional in a way, that 'organize' asks me in case it applies.

So I started to play around like this:

```yaml
   # ...
    actions:
      - echo: 'Some Notfication about the case: {path}'
      - shell: 'continue.sh'
```

and continue.sh is this:

```bash
#!/usr/bin/env bash
echo "Do you want to continue?"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) exit 0;;
        No ) exit 1;;
    esac
done
```

However, 'organize' does not stop the rule after that Exit 1, so I am a bit lost how to solve it.

Can you imagine that 'organize' could be more aware of the exit codes?
Is there a general rule on failing actions?
