### ISSUE TITLE
Preserve path option

### ISSUE THREAD

**Issue by dskaggs** [tfeldmann/organize#9]
It would be very helpful to have an option to replicate the file path from root of the source folder to the destination folder on a move or copy action. I subscribe to a system that downloads statements from over a dozen companies that I do business with and files them into a sub-folder for each account. I'd like to have an automated process run periodically to file those into a folder of the same name, but under the current year so that, at year's end, all the documents for that particular year are filed together

For instance, given the following input file:
`/source-folder/my-bank-name/monthly-statement-july.pdf`

move to the following destination file:
`/destination-folder/2018/my-bank-name/monthly-statement-july.pdf`

One idea might be to have a rule similar to the following:
```
rules:
  - folders: '/source-folder'
    subfolders: true
    filters:
      - Extension:
          - pdf
          - docx
      - LastModified
    actions:
      - Move: '/destination-folder/{lastmodified.year}/'
          - preservepath: true
```
Another might be even simpler:
```
rules:
  - folders: '/source-folder'
    subfolders: true
    filters:
      - Extension:
          - pdf
          - docx
      - LastModified
    actions:
      - Move: '/destination-folder/{lastmodified.year}/{path}/'
```
