### ISSUE TITLE
Renaming doesn't work when I try to Rename then Move

### ISSUE THREAD

**Issue by kawaiier** [tfeldmann/organize#91]
Hi!
I want all my files' extensions in Downloads folder be converted to lowercase and then moved to different folder depending on its file type.

I'm trying this code on **example.PDF** file
`rules:
  - folders: 
      - '~/Downloads'
    filters:
      - Extension
    actions:
      - rename: '{path.stem}.{extension.lower}'

  - folders: 
    - '~/Downloads'
    filters:
      - extension:
          - pdf
    actions:
      - move: '~/Documents/'`

As I run `organize sim` it says this file will be renamed and then moved to Documents but as I run `organize run` it just moves without renaming as **example.PDF** (not **example.pdf**)

**Comment by kawaiier** [comment]
As for now I've moved **rename** action into **move** action
```
- folders: 
    - '~/Downloads'
    filters:
      - extension:
          - pdf
    actions:
      - rename: '{path.stem}.{extension.lower}'
      - move: '~/Documents/'
```
