### ISSUE TITLE
Matched file is returned instead of duplicate, preventing removing the duplicate

### ISSUE THREAD

**Issue by asutekku** [tfeldmann/organize#93]
I'm trying to find all duplicates and then remove them. Finding duplicates works fine, but I'm having trouble deleting the duplicate since Organize returns the original file instead of the duplicate.

I am using the following rule, which is the same as in examples but with the added trash command at the end

    - folders:
          - ~/Downloads
      subfolders: true
      filters:
        - duplicate
      actions:
        - echo: "{path} is a duplicate of {duplicate}"
        - trash

However, if I run `organize sim`, I see the tool is trying to delete the original file. I can't assign the duplicate to the trash.

Unless I'm missing something, my suggestion is that using duplicate in filters could have an optional field to choose whether to match the duplicated file or original file. Something like:

    - folders:
          - ~/Downloads
      subfolders: true
      filters:
        - duplicate:
            match: first #for 1st duplicate, "original" for default behaviour or "all" for all duplicates
      actions:
        - echo: "{path} is a duplicate of {duplicate}"
        - trash

Additionally allow trash to have trash: duplicate.

**Comment by tfeldmann** [comment]
Thanks for the report and sorry for the late answer. I just released v2 in which you can define a duplicate detection method.
It is super easy to use:

[`duplicate` documentation](https://organize.readthedocs.io/en/latest/filters/#duplicate)

```yaml
rules:
  - name: "Check for duplicates on the Desktop. The older file is the original."
    locations:
      - ~/Desktop
    subfolders: true
    filters:
      - duplicate:
          detect_original_by: "created"
    actions:
      - echo: "Duplicate found!"
```

You can specify whether to detect the original file by the order in which they are seen, by name, by created date or by last modified date.

Have a great day!
