### ISSUE TITLE
Issues using FileContent Filter

### ISSUE THREAD

**Issue by jbajada** [tfeldmann/organize#96]
Im having issues outputting content found in a pdf based on a filecontent filter..

The config file looks as follows:

```
rules:
  - folders: /unprocessed
    filters:
      - extension: pdf
      - filecontent: '\d{1,2}\s(Jan(uary)?|Feb(ruary)?|Mar(ch)?|Apr(il)?|May|Jun(e)?|Jul(y)?|Aug(ust)?|Sep(tember)?|Oct(ober)?|Nov(ember)?|Dec(ember)?)\s+\d{4} (?P<letterdate>\w+)'
    actions:
      - echo: 'Rename file to {filecontent.letterdate}.pdf'
```

My sample pdf has multiple date values thoughout its contents in the following format:

```
XXXWWW
12 August 2020
Mr XXX YYY 11 Smith Drive 

This is a sample line with another date that should be ignored: 10 August 2020

Thank you
VVV
```

Is there a way to only get the first date in the sample file? 
Also, Is there a way to get either the 1st, 2nd, etc or last date value from the pdf file?

Thanks in advanced for anyone who can help out!
