### ISSUE TITLE
[Move] ERROR! 'created'

### ISSUE THREAD

**Issue by aweiher** [tfeldmann/organize#97]
Hi, 

I try to get started with a simple example from the docs - to move files  from the download to a subfolder of the creation date.

The python version I use is: `3.9.1`

My config looks like this:

```
rules:
  - folders: ~/Downloads
    subfolders: false
    filters:
      - filename:
          startswith: standard
      - extension: pdf
    actions:
        - move: '~/Downloads/{created.year}/pdfs/'
        - echo: "move to {path}"
```

The output is: 

```
aweiher@ac ~ % organize sim
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ SIMULATION ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Folder /home/aweiher/Downloads:
  File standard_200_4.pdf:
    - [Move] ERROR! 'created'
  File standard_200_4_compressed.pdf:
    - [Move] ERROR! 'created'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ SIMULATION ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

When I replace the created with an hard-coded value like this it works:

```
rules:
  - folders: ~/Downloads
    subfolders: false
    filters:
      - filename:
          startswith: standard
      - extension: pdf
    actions:
        - move: '~/Downloads/2021/pdfs/'
        - echo: "move to {path}"
```

```shell
aweiher@ac ~ % organize sim
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ SIMULATION ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Folder /home/aweiher/Downloads:
  File standard_200_4.pdf:
    - [Move] Move to "/home/aweiher/Downloads/2021/pdfs/standard_200_4.pdf"
    - [Echo] move to /home/aweiher/Downloads/2021/pdfs/standard_200_4.pdf
  File standard_200_4_compressed.pdf:
    - [Move] Move to "/home/aweiher/Downloads/2021/pdfs/standard_200_4_compressed.pdf"
    - [Echo] move to /home/aweiher/Downloads/2021/pdfs/standard_200_4_compressed.pdf
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ SIMULATION ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

As I saw usage examples like this at several places in the docs, like [here](https://organize.readthedocs.io/en/latest/page/filters.html?highlight=created#created), I ask myself what he problem could be.

**Comment by aweiher** [comment]
ok, typical case of rubberduck debugging. Directly after submitting the issue I saw that I have to add the `created` filter. Of course it works then.

```
rules:
  - folders: ~/Downloads
    subfolders: false
    filters:
      - filename:
          startswith: standard
      - extension: pdf
      - created
    actions:
        - move: '~/Downloads/{created.year}/pdfs/'
        - echo: "move to {path}"
```
